CREATE TABLE IF NOT EXISTS catalog_stock_items (
  id              SERIAL PRIMARY KEY,
  code            TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  category        TEXT,
  clinic_type     TEXT,
  presentation    TEXT,
  frequency_class TEXT
);

ALTER TABLE catalog_stock_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog_stock_read" ON catalog_stock_items
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_catalog_stock_name ON catalog_stock_items USING gin(to_tsvector('portuguese', name));
CREATE INDEX IF NOT EXISTS idx_catalog_stock_cat  ON catalog_stock_items(category);

INSERT INTO catalog_stock_items (code, name, category, clinic_type, presentation, frequency_class) VALUES
  ('ORT-001', 'Braquetes Metálicos (Caso Completo Roth/MBT)', 'Ortodontia', 'Odontologia', 'Kit (20 un)', 'Uso Contínuo'),
  ('ORT-002', 'Braquetes Cerâmicos / Safira', 'Ortodontia', 'Odontologia', 'Kit (20 un)', 'Uso Contínuo'),
  ('ORT-003', 'Fios Ortodônticos NiTi (Níquel-Titânio) - Vários Calibres', 'Ortodontia', 'Odontologia', 'Pacote (10 un)', 'Uso Contínuo'),
  ('ORT-004', 'Fios Ortodônticos Aço Inoxidável', 'Ortodontia', 'Odontologia', 'Pacote (10 un)', 'Uso Contínuo'),
  ('ORT-005', 'Elásticos em Cadeia (Corrente) - Várias Cores', 'Ortodontia', 'Odontologia', 'Rolo', 'Uso Contínuo'),
  ('ORT-006', 'Elásticos Intraorais (Leão, Raposa, etc.)', 'Ortodontia', 'Odontologia', 'Pacote (1000 un)', 'Uso Contínuo'),
  ('ORT-007', 'Alicates Ortodônticos (Corte de Amarrilho, Corte Distal, Weingart)', 'Instrumental Especializado', 'Odontologia', 'Unidade', 'Essencial (Orto)'),
  ('ORT-008', 'Tubos Ortodônticos de Colagem (Simples/Duplos)', 'Ortodontia', 'Odontologia', 'Pacote (10 un)', 'Uso Contínuo'),
  ('IMP-001', 'Implante Cone Morse / Hexágono Externo (Vários Diâmetros)', 'Implantodontia', 'Odontologia', 'Unidade', 'Uso Contínuo'),
  ('IMP-002', 'Kit Cirúrgico de Implantes (Fresas, Chaves, Catraca)', 'Implantodontia', 'Odontologia', 'Kit Completo', 'Essencial (Implante)'),
  ('IMP-003', 'Motor de Implante Odontológico com Bomba Peristáltica', 'Equipamento Cirúrgico', 'Odontologia', 'Unidade', 'Essencial (Implante)'),
  ('IMP-004', 'Enxerto Ósseo Liofilizado (Bovino/Sintético)', 'Cirurgia/Regeneração', 'Odontologia', 'Frasco (0.5g/1g)', 'Procedimento Específico'),
  ('IMP-005', 'Membrana Biológica de Colágeno (Regeneração Óssea Guiada)', 'Cirurgia/Regeneração', 'Odontologia', 'Unidade', 'Procedimento Específico'),
  ('IMP-006', 'Componentes Protéticos (Mini Pilar, Munhão Universal)', 'Implantodontia', 'Odontologia', 'Unidade', 'Reabilitação'),
  ('IMP-007', 'Soro Fisiológico Estéril c/ Equipo (Para Motor de Implante)', 'Cirurgia', 'Odontologia', 'Bolsa', 'Uso Contínuo'),
  ('PER-001', 'Curetas de Gracey (1-2, 5-6, 7-8, 11-12, 13-14)', 'Instrumental Especializado', 'Odontologia', 'Unidade/Kit', 'Essencial (Perio)'),
  ('PER-002', 'Curetas de McCall (13-14, 17-18)', 'Instrumental Especializado', 'Odontologia', 'Unidade/Kit', 'Essencial (Perio)'),
  ('PER-003', 'Sonda Periodontal Milimetrada (Williams/Carolina do Norte)', 'Instrumental de Exame', 'Odontologia', 'Unidade', 'Essencial (Perio)'),
  ('PER-004', 'Sonda de Nabers (Para Furca)', 'Instrumental de Exame', 'Odontologia', 'Unidade', 'Essencial (Perio)'),
  ('PER-005', 'Ponta Ultrassônica Perio (Para Raspador)', 'Acessório Equipamento', 'Odontologia', 'Unidade', 'Uso Contínuo'),
  ('PED-001', 'Coroas de Aço Inoxidável Pré-fabricadas (Infantil)', 'Odontopediatria', 'Odontologia', 'Kit/Unidade', 'Reabilitação Pediátrica'),
  ('PED-002', 'Abridor de Boca Infantil (Bite Block)', 'Acessório', 'Odontologia', 'Unidade', 'Essencial (Odontopediatria)'),
  ('PED-003', 'Fórceps Odontopediátricos (150S, 151S)', 'Instrumental Cirúrgico', 'Odontologia', 'Unidade', 'Essencial (Odontopediatria)'),
  ('PED-004', 'Flúor Diamino de Prata (Cariostático)', 'Odontopediatria', 'Odontologia', 'Frasco', 'Uso Contínuo'),
  ('PED-005', 'Material Restaurador Intermediário (IRM)', 'Restauradora', 'Odontologia', 'Kit', 'Uso Contínuo'),
  ('HOF-001', 'Toxina Botulínica Tipo A (50U, 100U)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Frasco-Ampola', 'Uso Contínuo'),
  ('HOF-002', 'Preenchedor de Ácido Hialurônico (Baixa/Média/Alta Reticulação)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Seringa (1ml)', 'Uso Contínuo'),
  ('HOF-003', 'Fios de Sustentação (PDO - Polidioxanona)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Pacote', 'Uso Contínuo'),
  ('HOF-004', 'Bioestimulador de Colágeno (Ácido Poli-L-Láctico / Hidroxiapatita)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Frasco/Seringa', 'Uso Contínuo'),
  ('HOF-005', 'Cânulas para Preenchimento (22G, 25G)', 'Material de Consumo', 'Ambos (HOF/Dermato)', 'Caixa', 'Uso Contínuo'),
  ('GIN-001', 'Espéculo Vaginal Descartável (P, M, G) com parafuso', 'Ginecologia', 'Medicina', 'Caixa (100 un)', 'Uso Contínuo'),
  ('GIN-002', 'Escova Endocervical e Espátula de Ayre (Kit Papanicolau)', 'Ginecologia', 'Medicina', 'Kit', 'Uso Contínuo'),
  ('GIN-003', 'Fixador Citológico Celular (Spray)', 'Ginecologia', 'Medicina', 'Frasco', 'Uso Contínuo'),
  ('GIN-004', 'Lâminas de Vidro com Extremidade Fosca (Citologia)', 'Laboratório', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('GIN-005', 'DIU - Dispositivo Intrauterino (Cobre / Prata / Hormonal)', 'Ginecologia', 'Medicina', 'Unidade', 'Procedimento Específico'),
  ('GIN-006', 'Doppler Fetal Portátil (Sonar)', 'Obstetrícia', 'Medicina', 'Unidade', 'Essencial (Obstetrícia)'),
  ('GIN-007', 'Gel Condutor para Ultrassom/Doppler', 'Ginecologia/Imagem', 'Medicina', 'Galão (5L)', 'Uso Contínuo'),
  ('CAR-001', 'Eletrodos Descartáveis para ECG (Adulto/Infantil)', 'Cardiologia', 'Medicina', 'Pacote (50 un)', 'Uso Contínuo'),
  ('CAR-002', 'Papel Termossensível para Eletrocardiógrafo', 'Cardiologia', 'Medicina', 'Rolo/Bloco', 'Uso Contínuo'),
  ('CAR-003', 'Holter 24h/48h (Aparelho e Gravador)', 'Equipamento Diagnóstico', 'Medicina', 'Unidade', 'Essencial (Cardio)'),
  ('CAR-004', 'M.A.P.A (Monitorização Ambulatorial da Pressão Arterial)', 'Equipamento Diagnóstico', 'Medicina', 'Unidade', 'Essencial (Cardio)'),
  ('CAR-005', 'Braçadeiras Sobressalentes para Esfigmomanômetro (Obeso/Pediátrico)', 'Cardiologia', 'Medicina', 'Unidade', 'Essencial'),
  ('DER-001', 'Dermatoscópio Manual (LED/Polarizado)', 'Dermatologia', 'Medicina', 'Unidade', 'Essencial (Dermato)'),
  ('DER-002', 'Nitrogênio Líquido (Botijão Criogênico e Cautério)', 'Dermatologia', 'Medicina', 'Equipamento/Refil', 'Procedimento Específico'),
  ('DER-003', 'Curetas Dermatológicas Descartáveis (Vários Tamanhos)', 'Dermatologia', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('DER-004', 'Punch para Biópsia de Pele (2mm, 3mm, 4mm, 5mm)', 'Cirurgia Menor', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('DER-005', 'Bisturi Elétrico/Termocautério Portátil', 'Cirurgia Menor', 'Ambos', 'Unidade', 'Essencial'),
  ('ORTP-001', 'Atadura de Gesso (Diversos Tamanhos 10cm, 15cm)', 'Ortopedia', 'Medicina', 'Pacote', 'Uso Contínuo'),
  ('ORTP-002', 'Malha Tubular de Algodão (Diversos Tamanhos)', 'Ortopedia', 'Medicina', 'Rolo', 'Uso Contínuo'),
  ('ORTP-003', 'Algodão Ortopédico (Manta)', 'Ortopedia', 'Medicina', 'Pacote', 'Uso Contínuo'),
  ('ORTP-004', 'Talas Metálicas Forradas com Espuma (Dedo/Punho)', 'Ortopedia', 'Medicina', 'Kit', 'Uso Contínuo'),
  ('ORTP-005', 'Fios de Kirschner (Cirurgia Ortopédica)', 'Cirurgia Maior', 'Medicina', 'Caixa', 'Procedimento Específico'),
  ('ORTP-006', 'Faixa Elástica / Atadura de Crepe', 'Ortopedia/Enfermagem', 'Medicina', 'Pacote', 'Uso Contínuo'),
  ('OFT-001', 'Colírios Diagnósticos (Dilatadores: Tropicamida / Ciclopentolato)', 'Oftalmologia', 'Medicina', 'Frasco', 'Uso Contínuo'),
  ('OFT-002', 'Colírio Anestésico (Proximetacaína)', 'Oftalmologia', 'Medicina', 'Frasco', 'Uso Contínuo'),
  ('OFT-003', 'Tiras de Schirmer (Teste de Secura Ocular)', 'Oftalmologia', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('OFT-004', 'Tiras de Fluoresceína Sódica', 'Oftalmologia', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('OFT-005', 'Caixa de Lentes de Prova e Armação de Teste', 'Equipamento Diagnóstico', 'Medicina', 'Kit Completo', 'Essencial (Oftalmo)'),
  ('OTO-001', 'Espéculos Auriculares (Plástico/Inox - Vários Tamanhos)', 'Otorrino', 'Medicina', 'Kit/Caixa', 'Uso Contínuo'),
  ('OTO-002', 'Espéculo Nasal de Killian', 'Instrumental de Exame', 'Medicina', 'Unidade', 'Essencial (Otorrino)'),
  ('OTO-003', 'Cânulas de Aspiração Auricular (Frazier)', 'Otorrino', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('OTO-004', 'Diapasão Médico (128Hz, 256Hz, 512Hz)', 'Instrumental de Exame', 'Medicina', 'Unidade/Kit', 'Essencial (Neurologia/Otorrino)'),
  ('OTO-005', 'Abaixador de Língua (Palito de Madeira)', 'Exame Físico', 'Ambos', 'Caixa (100 un)', 'Uso Diário'),
  ('URO-001', 'Sonda Vesical de Demora (Foley) - Vários Calibres', 'Urologia/Enfermagem', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('URO-002', 'Sonda de Alívio (Nelaton)', 'Urologia/Enfermagem', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('URO-003', 'Coletor de Urina Sistema Fechado (Bolsa)', 'Urologia/Enfermagem', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('URO-004', 'Xilocaína Geleia 2% (Lubrificante Uretral)', 'Material de Consumo', 'Medicina', 'Tubo', 'Uso Contínuo'),
  ('EMG-004', 'Cânula de Guedel (Vias Aéreas Orofaringeas - Tamanhos 0 a 5)', 'Emergência', 'Ambos', 'Kit', 'Carrinho de Emergência'),
  ('EMG-005', 'Ressuscitador Manual (Ambu) c/ Máscara Adulto/Pediátrico', 'Emergência', 'Ambos', 'Unidade', 'Carrinho de Emergência'),
  ('EMG-006', 'Tubos Endotraqueais (Com e Sem Balão - Vários Calibres)', 'Emergência/Cirurgia', 'Medicina', 'Caixa', 'Carrinho de Emergência'),
  ('EMG-007', 'Laringoscópio com Lâminas Curvas e Retas (Macintosh/Miller)', 'Emergência', 'Medicina', 'Kit', 'Carrinho de Emergência'),
  ('EMG-008', 'Cateter Venoso Periférico (Jelco / Abocath - 14G a 24G)', 'Enfermagem/Acesso', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('EMG-009', 'Soro Ringer Lactato / Glicosado 5%', 'Medicação/Fluidos', 'Medicina', 'Bolsa (500ml)', 'Uso Contínuo'),
  ('EMG-010', 'Medicações de Emergência (Adrenalina, Atropina, Amiodarona)', 'Medicação', 'Ambos', 'Ampolas', 'Carrinho de Emergência'),
  ('LAB-001', 'Tubos de Coleta de Sangue (Tampa Roxa - EDTA)', 'Laboratório', 'Medicina', 'Rack (100 un)', 'Exames'),
  ('LAB-002', 'Tubos de Coleta de Sangue (Tampa Amarela/Vermelha - Sorologia)', 'Laboratório', 'Medicina', 'Rack (100 un)', 'Exames'),
  ('LAB-003', 'Tubos de Coleta de Sangue (Tampa Azul - Coagulação)', 'Laboratório', 'Medicina', 'Rack (100 un)', 'Exames'),
  ('LAB-004', 'Agulhas para Coleta Múltipla a Vácuo', 'Laboratório', 'Medicina', 'Caixa', 'Exames'),
  ('LAB-005', 'Adaptador (Canhão) para Coleta a Vácuo', 'Laboratório', 'Medicina', 'Pacote', 'Exames'),
  ('LAB-006', 'Garrote (Torniquete) Elástico', 'Enfermagem/Laboratório', 'Medicina', 'Unidade', 'Uso Contínuo');

