INSERT INTO catalog_procedures (code, name, category, specialty, type, duration_min) VALUES
  ('OD-001', 'Consulta de avaliação inicial', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 60),
  ('OD-002', 'Consulta de retorno', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-003', 'Exame clínico completo', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 45),
  ('OD-004', 'Planejamento de tratamento', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-005', 'Fotografias clínicas intraorais', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-006', 'Moldagem de estudo – por arcada', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-007', 'Escaneamento digital intraoral', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-008', 'Teste de vitalidade pulpar', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-009', 'Planejamento digital de sorriso (DSD)', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 60),
  ('OD-010', 'Documentação ortodôntica completa', 'Avaliação e Diagnóstico', 'Ortodontia', 'Odontológico', 60),
  ('OD-011', 'Radiografia periapical – por dente', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 10),
  ('OD-012', 'Radiografia panorâmica', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 15),
  ('OD-013', 'Radiografia interproximal – bite-wing (por par)', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 15),
  ('OD-014', 'Radiografia oclusal', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 10),
  ('OD-015', 'Tomografia computadorizada CBCT – arco completo', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 20),
  ('OD-016', 'Tomografia computadorizada CBCT – região segmentar', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 20),
  ('OD-017', 'Telerradiografia lateral de crânio', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 15),
  ('OD-018', 'Profilaxia dental – limpeza', 'Prevenção e Profilaxia', 'Odontologia Geral', 'Odontológico', 45),
  ('OD-019', 'Raspagem coronária supragengival', 'Prevenção e Profilaxia', 'Periodontia', 'Odontológico', 60),
  ('OD-020', 'Aplicação tópica de flúor', 'Prevenção e Profilaxia', 'Odontologia Geral', 'Odontológico', 15),
  ('OD-021', 'Selante de fissura – por dente', 'Prevenção e Profilaxia', 'Odontopediatria', 'Odontológico', 20),
  ('OD-022', 'Orientação de higiene oral', 'Prevenção e Profilaxia', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-023', 'Consulta de manutenção periodontal', 'Prevenção e Profilaxia', 'Periodontia', 'Odontológico', 60),
  ('OD-024', 'Aplicação de cariostático IASF – por dente', 'Prevenção e Profilaxia', 'Odontopediatria', 'Odontológico', 10),
  ('OD-025', 'Raspagem e alisamento radicular – por sextante', 'Periodontia', 'Periodontia', 'Odontológico', 60),
  ('OD-026', 'Curetagem subgengival – por sextante', 'Periodontia', 'Periodontia', 'Odontológico', 60),
  ('OD-027', 'Gengivectomia / gengivoplastia', 'Periodontia', 'Periodontia', 'Odontológico', 90),
  ('OD-028', 'Cirurgia periodontal a retalho – por sextante', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-029', 'Enxerto gengival livre', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-030', 'Enxerto de tecido conjuntivo subepitelial', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-031', 'Cirurgia de aumento de coroa clínica – por dente', 'Periodontia', 'Periodontia', 'Odontológico', 90),
  ('OD-032', 'Frenectomia labial / lingual', 'Periodontia', 'Cirurgia Oral', 'Odontológico', 60),
  ('OD-033', 'Recobrimento radicular – por dente', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-034', 'Regeneração óssea guiada', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-035', 'Restauração resina composta classe I – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-036', 'Restauração resina composta classe II – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-037', 'Restauração resina composta classe III – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-038', 'Restauração resina composta classe IV – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-039', 'Restauração resina composta classe V – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 30),
  ('OD-040', 'Restauração amálgama classe I', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-041', 'Restauração amálgama classe II', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-042', 'Troca / substituição de restauração', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-043', 'Cimentação de pino intracanal – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-044', 'Núcleo de preenchimento – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-045', 'Onlay em resina composta', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 90),
  ('OD-046', 'Inlay em resina composta', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 90),
  ('OD-047', 'Overlay em resina composta', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 90),
  ('OD-048', 'Tratamento endodôntico – dente unirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 90),
  ('OD-049', 'Tratamento endodôntico – dente birradicular', 'Endodontia', 'Endodontia', 'Odontológico', 120),
  ('OD-050', 'Tratamento endodôntico – dente multirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 150),
  ('OD-051', 'Retratamento endodôntico – dente unirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 120),
  ('OD-052', 'Retratamento endodôntico – dente birradicular', 'Endodontia', 'Endodontia', 'Odontológico', 150),
  ('OD-053', 'Retratamento endodôntico – dente multirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 180),
  ('OD-054', 'Apicectomia – por dente', 'Endodontia', 'Endodontia', 'Odontológico', 120),
  ('OD-055', 'Capeamento pulpar direto', 'Endodontia', 'Endodontia', 'Odontológico', 60),
  ('OD-056', 'Capeamento pulpar indireto', 'Endodontia', 'Endodontia', 'Odontológico', 45),
  ('OD-057', 'Pulpotomia', 'Endodontia', 'Endodontia', 'Odontológico', 60),
  ('OD-058', 'Biopulpectomia', 'Endodontia', 'Endodontia', 'Odontológico', 90),
  ('OD-059', 'Necropulpectomia', 'Endodontia', 'Endodontia', 'Odontológico', 90),
  ('OD-060', 'Medicação intracanal – curativo por sessão', 'Endodontia', 'Endodontia', 'Odontológico', 30),
  ('OD-061', 'Exodontia de dente permanente', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 45),
  ('OD-062', 'Exodontia de dente decíduo', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 30),
  ('OD-063', 'Exodontia de dente semi-incluso', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 90),
  ('OD-064', 'Exodontia de siso incluso – dente do juízo', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 120),
  ('OD-065', 'Alveoloplastia – por região', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 60),
  ('OD-066', 'Excisão de cisto odontogênico', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 90),
  ('OD-067', 'Biópsia de tecido mole oral', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 45),
  ('OD-068', 'Reimplante dental', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 90),
  ('OD-069', 'Levantamento de seio maxilar – sinus lift', 'Cirurgia Oral', 'Implantodontia', 'Odontológico', 180),
  ('OD-070', 'Enxerto ósseo em bloco', 'Cirurgia Oral', 'Implantodontia', 'Odontológico', 180),
  ('OD-071', 'Enxerto ósseo particulado', 'Cirurgia Oral', 'Implantodontia', 'Odontológico', 120),
  ('OD-072', 'Instalação de implante osseointegrado – por implante', 'Implantodontia', 'Implantodontia', 'Odontológico', 120),
  ('OD-073', 'Reabertura de implante – 2ª fase cirúrgica', 'Implantodontia', 'Implantodontia', 'Odontológico', 45),
  ('OD-074', 'Instalação de cicatrizador gengival – por implante', 'Implantodontia', 'Implantodontia', 'Odontológico', 30),
  ('OD-075', 'Moldagem para prótese sobre implante', 'Implantodontia', 'Implantodontia', 'Odontológico', 45),
  ('OD-076', 'Coroa sobre implante – unitária', 'Implantodontia', 'Implantodontia', 'Odontológico', 60),
  ('OD-077', 'Protocolo fixo sobre implantes – por arco', 'Implantodontia', 'Implantodontia', 'Odontológico', 120),
  ('OD-078', 'Overdenture sobre implantes – por arco', 'Implantodontia', 'Implantodontia', 'Odontológico', 90),
  ('OD-079', 'Implante carga imediata – unitário', 'Implantodontia', 'Implantodontia', 'Odontológico', 150),
  ('OD-080', 'Remoção de implante osseointegrado', 'Implantodontia', 'Implantodontia', 'Odontológico', 90),
  ('OD-081', 'Coroa metalocerâmica – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-082', 'Coroa total cerâmica e-max – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-083', 'Coroa total zircônia – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-084', 'Coroa provisória – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 45),
  ('OD-085', 'Faceta de porcelana – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-086', 'Faceta de resina direta – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-087', 'Inlay cerâmico – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-088', 'Onlay cerâmico – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-089', 'Prótese parcial removível PPR – por arco', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-090', 'Prótese total convencional – por arco', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-091', 'Prótese parcial fixa – por elemento ponteado', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-092', 'Reembasamento de prótese', 'Prótese', 'Prótese Dentária', 'Odontológico', 45),
  ('OD-093', 'Reparação / conserto de prótese', 'Prótese', 'Prótese Dentária', 'Odontológico', 30),
  ('OD-094', 'Cimentação de prótese fixa', 'Prótese', 'Prótese Dentária', 'Odontológico', 45),
  ('OD-095', 'Instalação de aparelho fixo metálico – arco completo', 'Ortodontia', 'Ortodontia', 'Odontológico', 90),
  ('OD-096', 'Instalação de aparelho fixo estético cerâmico / safira', 'Ortodontia', 'Ortodontia', 'Odontológico', 90),
  ('OD-097', 'Instalação de alinhadores invisíveis – arco completo', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-098', 'Manutenção mensal de aparelho fixo', 'Ortodontia', 'Ortodontia', 'Odontológico', 30),
  ('OD-099', 'Instalação de aparelho ortopédico funcional', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-100', 'Contenção removível – por arco', 'Ortodontia', 'Ortodontia', 'Odontológico', 30),
  ('OD-101', 'Contenção fixa colada', 'Ortodontia', 'Ortodontia', 'Odontológico', 45),
  ('OD-102', 'Expansor de palato RPE', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-103', 'Distalizador de molar', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-104', 'Remoção de aparelho fixo', 'Ortodontia', 'Ortodontia', 'Odontológico', 45),
  ('OD-105', 'Placa de mordida / placa de bruxismo ortodôntica', 'Ortodontia', 'Ortodontia', 'Odontológico', 45),
  ('OD-106', 'Consulta de avaliação infantil', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 45),
  ('OD-107', 'Restauração em resina composta – dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 45),
  ('OD-108', 'Coroa de aço inoxidável – por dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 60),
  ('OD-109', 'Pulpotomia em dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 60),
  ('OD-110', 'Pulpectomia em dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 90),
  ('OD-111', 'Aparelho para manutenção de espaço', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 60),
  ('OD-112', 'Orientação de hábitos bucais', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 30),
  ('OD-113', 'Tratamento restaurador atraumático ART', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 30),
  ('OD-114', 'Clareamento dental de consultório – por sessão', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-115', 'Clareamento dental caseiro – moldeira + gel', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 45),
  ('OD-116', 'Clareamento dental combinado consultório + caseiro', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-117', 'Microabrasão do esmalte – por dente', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 30),
  ('OD-118', 'Fechamento de diastema em resina direta', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-119', 'Remodelação estética com resina – por dente', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-120', 'Planejamento digital do sorriso', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 60),
  ('OD-121', 'Placa miorrelaxante bruxismo termoformada', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 45),
  ('OD-122', 'Placa miorrelaxante rígida usinada / fresada', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 45),
  ('OD-123', 'Placa de avanço mandibular – ronco / apneia', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 45),
  ('OD-124', 'Ajuste oclusal / desgaste seletivo', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 60),
  ('OD-125', 'Tratamento de disfunção temporomandibular DTM', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 60),
  ('OD-126', 'Toxina botulínica bruxismo masseter – por lado', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 30),
  ('OD-127', 'Ácido hialurônico labial – harmonização dental', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 45),
  ('OD-128', 'Sutura de tecido oral', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 30),
  ('OD-129', 'Retirada de pontos orais', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 15),
  ('OD-130', 'Drenagem de abscesso dentoalveolar', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 45),
  ('MD-001', 'Consulta clínica geral', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 30),
  ('MD-002', 'Consulta de retorno clínico', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 20),
  ('MD-003', 'Consulta de urgência / pronto atendimento', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 30),
  ('MD-004', 'Avaliação pré-operatória', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 45),
  ('MD-005', 'Avaliação admissional – medicina do trabalho', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-006', 'Avaliação periódica – medicina do trabalho', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-007', 'Avaliação de retorno ao trabalho', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-008', 'Avaliação para mudança de função', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-009', 'Atestado médico', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-010', 'Declaração médica', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-011', 'Receita médica – emissão', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-012', 'Solicitação de exames laboratoriais', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-013', 'Avaliação pré-anestésica', 'Consultas e Avaliações', 'Anestesiologia', 'Médico', 45),
  ('MD-014', 'Segunda opinião médica', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 60),
  ('MD-015', 'Teleconsulta / consulta online', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 30),
  ('MD-016', 'Consulta domiciliar', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 60),
  ('MD-017', 'Consulta de medicina preventiva – check-up', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 60),
  ('MD-018', 'Consulta cardiológica', 'Cardiologia', 'Cardiologia', 'Médico', 45),
  ('MD-019', 'Retorno cardiológico', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-020', 'Eletrocardiograma ECG', 'Cardiologia', 'Cardiologia', 'Médico', 15),
  ('MD-021', 'Ecocardiograma transtorácico', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-022', 'Ecocardiograma transesofágico', 'Cardiologia', 'Cardiologia', 'Médico', 90),
  ('MD-023', 'Ecocardiograma de estresse com dobutamina', 'Cardiologia', 'Cardiologia', 'Médico', 90),
  ('MD-024', 'Teste ergométrico – esteira', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-025', 'Holter 24 horas – instalação + interpretação', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-026', 'Holter 7 dias', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-027', 'MAPA – monitorização ambulatorial da pressão arterial', 'Cardiologia', 'Cardiologia', 'Médico', 20),
  ('MD-028', 'Teste de mesa inclinada – tilt test', 'Cardiologia', 'Cardiologia', 'Médico', 90),
  ('MD-029', 'Cardioversão elétrica eletiva', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-030', 'Avaliação de marca-passo implantado', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-031', 'Angiotomografia coronariana', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-032', 'Score de cálcio coronariano', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-033', 'Avaliação de insuficiência cardíaca', 'Cardiologia', 'Cardiologia', 'Médico', 45),
  ('MD-034', 'Consulta de hipertensão arterial sistêmica', 'Cardiologia', 'Cardiologia', 'Médico', 40),
  ('MD-035', 'Consulta dermatológica', 'Dermatologia', 'Dermatologia', 'Médico', 40),
  ('MD-036', 'Retorno dermatológico', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-037', 'Dermatoscopia – por lesão', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-038', 'Mapeamento corporal – dermatoscopia digital', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-039', 'Biópsia de pele punch', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-040', 'Biópsia excisional de pele', 'Dermatologia', 'Dermatologia', 'Médico', 45),
  ('MD-041', 'Criocirurgia – crioterapia por lesão', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-042', 'Eletrocauterização por lesão', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-043', 'Excisão de lesão cutânea benigna', 'Dermatologia', 'Dermatologia', 'Médico', 45),
  ('MD-044', 'Excisão de lesão cutânea maligna com margem', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-045', 'Curetagem de lesão cutânea', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-046', 'Peeling químico superficial AHA / BHA', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-047', 'Peeling químico médio TCA', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-048', 'Peeling químico profundo – fenol', 'Dermatologia', 'Dermatologia', 'Médico', 120),
  ('MD-049', 'Laser ablativo por sessão / região', 'Dermatologia', 'Dermatologia', 'Médico', 90),
  ('MD-050', 'Laser não ablativo por sessão / região', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-051', 'Fototerapia UVB narrowband – por sessão', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-052', 'PUVA terapia – por sessão', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-053', 'Excisão de unha / onicogrifose', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-054', 'Plástica ungueal – unha encravada', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-055', 'Microagulhamento clínico – por sessão', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-056', 'Consulta ginecológica', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 40),
  ('MD-057', 'Retorno ginecológico', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 25),
  ('MD-058', 'Consulta de pré-natal – 1º trimestre', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 45),
  ('MD-059', 'Consulta de pré-natal – 2º trimestre', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 40),
  ('MD-060', 'Consulta de pré-natal – 3º trimestre', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 40),
  ('MD-061', 'Consulta puerperal – pós-parto', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 40),
  ('MD-062', 'Coleta de Papanicolau – colpocitologia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-063', 'Colposcopia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-064', 'Biópsia de colo uterino – punch', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-065', 'LEEP – conização com alça diatérmica', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 60),
  ('MD-066', 'Inserção de DIU', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-067', 'Remoção de DIU', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-068', 'Inserção de implante anticoncepcional subdérmico', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-069', 'Remoção de implante anticoncepcional subdérmico', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-070', 'Histeroscopia diagnóstica', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 45);