INSERT INTO catalog_procedures (code, name, category, specialty, type, duration_min) VALUES
  ('MD-071', 'Histeroscopia cirúrgica – polipectomia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 60),
  ('MD-072', 'Vulvoscopia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-073', 'Biópsia de vulva', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-074', 'Consulta de climatério / menopausa', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 45),
  ('MD-075', 'Avaliação de disfunção sexual feminina', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 45),
  ('MD-076', 'Consulta pediátrica geral', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-077', 'Retorno pediátrico', 'Pediatria', 'Pediatria', 'Médico', 25),
  ('MD-078', 'Puericultura – neonato 0 a 28 dias', 'Pediatria', 'Pediatria', 'Médico', 45),
  ('MD-079', 'Puericultura – lactente 1 a 6 meses', 'Pediatria', 'Pediatria', 'Médico', 45),
  ('MD-080', 'Puericultura – lactente 6 a 12 meses', 'Pediatria', 'Pediatria', 'Médico', 45),
  ('MD-081', 'Puericultura – criança 1 a 4 anos', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-082', 'Puericultura – criança 5 a 10 anos', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-083', 'Consulta do adolescente 11 a 19 anos', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-084', 'Avaliação do desenvolvimento neuropsicomotor', 'Pediatria', 'Pediatria', 'Médico', 60),
  ('MD-085', 'Triagem auditiva neonatal – EOA', 'Pediatria', 'Pediatria', 'Médico', 20),
  ('MD-086', 'Triagem visual neonatal – teste do olhinho', 'Pediatria', 'Pediatria', 'Médico', 15),
  ('MD-087', 'Teste do pezinho ampliado', 'Pediatria', 'Pediatria', 'Médico', 15),
  ('MD-088', 'Vacinação – por dose', 'Pediatria', 'Pediatria', 'Médico', 10),
  ('MD-089', 'Avaliação de crescimento e peso', 'Pediatria', 'Pediatria', 'Médico', 20),
  ('MD-090', 'Teste SNAP-IV – avaliação de TDAH', 'Pediatria', 'Pediatria', 'Médico', 30),
  ('MD-091', 'Consulta ortopédica', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 40),
  ('MD-092', 'Retorno ortopédico', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-093', 'Imobilização gessada – por segmento', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-094', 'Retirada de gesso', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 15),
  ('MD-095', 'Artrocentese – joelho', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-096', 'Artrocentese – ombro', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-097', 'Artrocentese – tornozelo', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-098', 'Infiltração articular com corticosteroide – joelho', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-099', 'Infiltração articular com ácido hialurônico – joelho', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-100', 'Infiltração periarticular – tendão / bursa', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-101', 'Bloqueio nervoso periférico', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-102', 'Redução de fratura sem fixação', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 60),
  ('MD-103', 'Aplicação de órtese / imobilizador – por segmento', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-104', 'Avaliação de força muscular e amplitude articular', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-105', 'Avaliação pré-cirúrgica ortopédica', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 45),
  ('MD-106', 'Avaliação fisioterapêutica', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-107', 'Sessão de fisioterapia ortopédica / musculoesquelética', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-108', 'Sessão de fisioterapia neurológica', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-109', 'Sessão de RPG – reeducação postural global', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-110', 'Sessão de pilates clínico individual', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-111', 'Dry needling – agulhamento a seco – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 45),
  ('MD-112', 'Ultrassom terapêutico – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-113', 'TENS – eletroestimulação nervosa transcutânea', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-114', 'FES – estimulação elétrica funcional', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-115', 'Liberação miofascial – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-116', 'Terapia manual / mobilização articular', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-117', 'Fisioterapia respiratória – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 45),
  ('MD-118', 'Fisioterapia pélvica / uroginecológica – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-119', 'Hidroterapia / cinesioterapia aquática – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-120', 'Ventosaterapia – cupping', 'Fisioterapia', 'Fisioterapia', 'Médico', 45),
  ('MD-121', 'Kinesio taping – aplicação por região', 'Fisioterapia', 'Fisioterapia', 'Médico', 20),
  ('MD-122', 'Tração cervical / lombar – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-123', 'Laser de baixa intensidade LLLT – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-124', 'Ondas de choque extracorpórea – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-125', 'Consulta neurológica', 'Neurologia', 'Neurologia', 'Médico', 45),
  ('MD-126', 'Retorno neurológico', 'Neurologia', 'Neurologia', 'Médico', 30),
  ('MD-127', 'Eletroencefalograma EEG', 'Neurologia', 'Neurologia', 'Médico', 60),
  ('MD-128', 'EEG com privação do sono', 'Neurologia', 'Neurologia', 'Médico', 90),
  ('MD-129', 'Eletroneuromiografia ENMG', 'Neurologia', 'Neurologia', 'Médico', 90),
  ('MD-130', 'Velocidade de condução nervosa – VCN', 'Neurologia', 'Neurologia', 'Médico', 60),
  ('MD-131', 'Avaliação neuropsicológica', 'Neurologia', 'Neurologia', 'Médico', 120),
  ('MD-132', 'Avaliação de tontura e equilíbrio – otoneurologia', 'Neurologia', 'Neurologia', 'Médico', 60),
  ('MD-133', 'Avaliação e tratamento de cefaleia – enxaqueca', 'Neurologia', 'Neurologia', 'Médico', 45),
  ('MD-134', 'Toxina botulínica para enxaqueca crônica', 'Neurologia', 'Neurologia', 'Médico', 45),
  ('MD-135', 'Consulta endocrinológica', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-136', 'Retorno endocrinológico', 'Endocrinologia', 'Endocrinologia', 'Médico', 30),
  ('MD-137', 'Avaliação e controle de diabetes tipo 1', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-138', 'Avaliação e controle de diabetes tipo 2', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-139', 'Avaliação e tratamento de hipotireoidismo', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-140', 'Avaliação e tratamento de hipertireoidismo', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-141', 'Avaliação e tratamento de dislipidemia', 'Endocrinologia', 'Endocrinologia', 'Médico', 30),
  ('MD-142', 'Avaliação de obesidade e sobrepeso', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-143', 'Avaliação de osteoporose e osteopenia', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-144', 'Avaliação hormonal masculina / TRT', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-145', 'Consulta de síndrome metabólica', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-146', 'Consulta oftalmológica', 'Oftalmologia', 'Oftalmologia', 'Médico', 40),
  ('MD-147', 'Retorno oftalmológico', 'Oftalmologia', 'Oftalmologia', 'Médico', 20),
  ('MD-148', 'Refração / prescrição de óculos', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-149', 'Tonometria de aplanação', 'Oftalmologia', 'Oftalmologia', 'Médico', 15),
  ('MD-150', 'Mapeamento de retina', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-151', 'Retinografia colorida', 'Oftalmologia', 'Oftalmologia', 'Médico', 20),
  ('MD-152', 'OCT – tomografia de coerência óptica', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-153', 'Campimetria / perimetria computadorizada', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-154', 'Paquimetria corneal', 'Oftalmologia', 'Oftalmologia', 'Médico', 15),
  ('MD-155', 'Topografia corneal', 'Oftalmologia', 'Oftalmologia', 'Médico', 20),
  ('MD-156', 'Adaptação de lentes de contato', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-157', 'Aplicação de laser na retina – por sessão', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-158', 'Injeção intravítrea – por olho', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-159', 'Avaliação e tratamento de estrabismo', 'Oftalmologia', 'Oftalmologia', 'Médico', 45),
  ('MD-160', 'Consulta ORL – otorrinolaringológica', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 40),
  ('MD-161', 'Retorno ORL', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-162', 'Audiometria tonal liminar', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-163', 'Audiometria vocal – logoaudiometria', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-164', 'Imitanciometria – timpanometria', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-165', 'Pesquisa do reflexo estapediano', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 15),
  ('MD-166', 'Laringoscopia direta / videolaringoscopia', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-167', 'Nasofibroscopia', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-168', 'Lavagem auricular / ceruminolítico', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-169', 'Punção de seio paranasal – sinusite', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-170', 'Manobra de Epley – VPPB', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-171', 'Consulta psiquiátrica', 'Psiquiatria', 'Psiquiatria', 'Médico', 60),
  ('MD-172', 'Retorno psiquiátrico', 'Psiquiatria', 'Psiquiatria', 'Médico', 30),
  ('MD-173', 'Avaliação psiquiátrica diagnóstica completa', 'Psiquiatria', 'Psiquiatria', 'Médico', 90),
  ('MD-174', 'Avaliação psiquiátrica pericial / forense', 'Psiquiatria', 'Psiquiatria', 'Médico', 120),
  ('MD-175', 'Psicoterapia individual – médico – por sessão', 'Psiquiatria', 'Psiquiatria', 'Médico', 50),
  ('MD-176', 'Psicoterapia individual – psicólogo – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-177', 'Terapia cognitivo-comportamental TCC – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-178', 'EMDR – por sessão', 'Psicologia', 'Psicologia', 'Médico', 60),
  ('MD-179', 'Avaliação psicológica – laudo completo', 'Psicologia', 'Psicologia', 'Médico', 120),
  ('MD-180', 'Psicoterapia de casal – por sessão', 'Psicologia', 'Psicologia', 'Médico', 60),
  ('MD-181', 'Psicoterapia familiar – por sessão', 'Psicologia', 'Psicologia', 'Médico', 60),
  ('MD-182', 'Terapia de aceitação e compromisso ACT – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-183', 'Terapia dialética comportamental DBT – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-184', 'Avaliação neuropsicológica – laudo', 'Psicologia', 'Neuropsicologia', 'Médico', 180),
  ('MD-185', 'Consulta urológica', 'Urologia', 'Urologia', 'Médico', 40),
  ('MD-186', 'Retorno urológico', 'Urologia', 'Urologia', 'Médico', 20),
  ('MD-187', 'Urofluxometria', 'Urologia', 'Urologia', 'Médico', 30),
  ('MD-188', 'Urodinâmica completa', 'Urologia', 'Urologia', 'Médico', 60),
  ('MD-189', 'Cistoscopia diagnóstica', 'Urologia', 'Urologia', 'Médico', 30),
  ('MD-190', 'Calibração uretral', 'Urologia', 'Urologia', 'Médico', 20),
  ('MD-191', 'Vasectomia – procedimento ambulatorial', 'Urologia', 'Urologia', 'Médico', 60),
  ('MD-192', 'Biópsia de próstata transretal – avaliação', 'Urologia', 'Urologia', 'Médico', 30),
  ('MD-193', 'Avaliação de disfunção erétil', 'Urologia', 'Urologia', 'Médico', 45),
  ('MD-194', 'Avaliação de infertilidade masculina', 'Urologia', 'Urologia', 'Médico', 45),
  ('MD-195', 'Consulta gastroenterológica', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 40),
  ('MD-196', 'Retorno gastroenterológico', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 25),
  ('MD-197', 'Endoscopia digestiva alta EDA', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-198', 'Colonoscopia', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 60),
  ('MD-199', 'Retossigmoidoscopia flexível', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-200', 'Biópsia endoscópica', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-201', 'Teste respiratório para H. pylori', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-202', 'Manometria esofágica de alta resolução', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 60),
  ('MD-203', 'pHmetria esofágica 24h – interpretação', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-204', 'Avaliação de doença inflamatória intestinal', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 45),
  ('MD-205', 'Consulta nutricional', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-206', 'Retorno nutricional', 'Nutrição', 'Nutrição', 'Médico', 30),
  ('MD-207', 'Avaliação antropométrica completa', 'Nutrição', 'Nutrição', 'Médico', 45),
  ('MD-208', 'Plano alimentar personalizado', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-209', 'Avaliação nutricional para esportistas', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-210', 'Avaliação nutricional pediátrica', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-211', 'Consulta de nutrologia', 'Nutrologia', 'Nutrologia', 'Médico', 45),
  ('MD-212', 'Retorno nutrológico', 'Nutrologia', 'Nutrologia', 'Médico', 30),
  ('MD-213', 'Avaliação de composição corporal – bioimpedância', 'Nutrologia', 'Nutrologia', 'Médico', 30),
  ('MD-214', 'Avaliação para reeducação alimentar', 'Nutrologia', 'Nutrologia', 'Médico', 45),
  ('MD-215', 'Protocolo de emagrecimento supervisionado', 'Nutrologia', 'Nutrologia', 'Médico', 60),
  ('MD-216', 'Consulta reumatológica', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-217', 'Retorno reumatológico', 'Reumatologia', 'Reumatologia', 'Médico', 30),
  ('MD-218', 'Avaliação de artrite reumatoide', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-219', 'Avaliação de lúpus eritematoso sistêmico', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-220', 'Avaliação de espondiloartrite / espondilite anquilosante', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-221', 'Avaliação de fibromialgia', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-222', 'Avaliação e tratamento de gota', 'Reumatologia', 'Reumatologia', 'Médico', 30),
  ('MD-223', 'Avaliação de síndrome de Sjögren', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-224', 'Infiltração articular reumatológica – por articulação', 'Reumatologia', 'Reumatologia', 'Médico', 30),
  ('MD-225', 'Consulta pneumológica', 'Pneumologia', 'Pneumologia', 'Médico', 40),
  ('MD-226', 'Retorno pneumológico', 'Pneumologia', 'Pneumologia', 'Médico', 25),
  ('MD-227', 'Espirometria com broncodilatador', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-228', 'Espirometria simples', 'Pneumologia', 'Pneumologia', 'Médico', 30),
  ('MD-229', 'Pico de fluxo expiratório – peak flow', 'Pneumologia', 'Pneumologia', 'Médico', 15),
  ('MD-230', 'Teste de caminhada de 6 minutos', 'Pneumologia', 'Pneumologia', 'Médico', 30),
  ('MD-231', 'Oximetria noturna', 'Pneumologia', 'Pneumologia', 'Médico', 20),
  ('MD-232', 'Avaliação de asma grave', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-233', 'Avaliação e tratamento de DPOC', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-234', 'Avaliação de apneia obstrutiva do sono', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-235', 'Consulta infectológica', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-236', 'Retorno infectológico', 'Infectologia', 'Infectologia', 'Médico', 30),
  ('MD-237', 'Avaliação e tratamento de HIV / AIDS', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-238', 'Avaliação de hepatites virais B e C', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-239', 'Avaliação pós-exposição a material biológico', 'Infectologia', 'Infectologia', 'Médico', 30),
  ('MD-240', 'Consulta de medicina de viagem', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-241', 'Consulta imunológica / alergológica', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 45),
  ('MD-242', 'Retorno alergia / imunologia', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 30),
  ('MD-243', 'Teste de alergia – prick test por bateria', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 60),
  ('MD-244', 'Teste de contato – patch test', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 60),
  ('MD-245', 'Teste de provocação oral – alimento / medicamento', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 120),
  ('MD-246', 'Imunoterapia – vacina alergênica por sessão', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 20),
  ('MD-247', 'Avaliação de imunodeficiência primária', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 60),
  ('MD-248', 'Consulta nefrológica', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-249', 'Retorno nefrológico', 'Nefrologia', 'Nefrologia', 'Médico', 30),
  ('MD-250', 'Avaliação de doença renal crônica', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-251', 'Avaliação de hipertensão arterial resistente', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-252', 'Avaliação de nefrolitíase – cálculo renal', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-253', 'Avaliação de glomerulonefrite', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-254', 'Consulta hepatológica', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-255', 'Retorno hepatológico', 'Hepatologia', 'Hepatologia', 'Médico', 30),
  ('MD-256', 'Avaliação de esteatose hepática – gordura no fígado', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-257', 'Avaliação de cirrose hepática', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-258', 'Avaliação de hepatite autoimune', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-259', 'Consulta hematológica', 'Hematologia', 'Hematologia', 'Médico', 45),
  ('MD-260', 'Retorno hematológico', 'Hematologia', 'Hematologia', 'Médico', 30),
  ('MD-261', 'Avaliação de anemia', 'Hematologia', 'Hematologia', 'Médico', 30),
  ('MD-262', 'Avaliação de coagulopatia / distúrbio hemorrágico', 'Hematologia', 'Hematologia', 'Médico', 45),
  ('MD-263', 'Avaliação de trombofilia', 'Hematologia', 'Hematologia', 'Médico', 45),
  ('MD-264', 'Consulta oncológica – avaliação diagnóstica', 'Oncologia', 'Oncologia Clínica', 'Médico', 60),
  ('MD-265', 'Retorno oncológico', 'Oncologia', 'Oncologia Clínica', 'Médico', 45),
  ('MD-266', 'Avaliação de resposta ao tratamento oncológico', 'Oncologia', 'Oncologia Clínica', 'Médico', 60),
  ('MD-267', 'Consulta de cuidados paliativos', 'Oncologia', 'Cuidados Paliativos', 'Médico', 60),
  ('MD-268', 'Consulta de angiologia / cirurgia vascular', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 40),
  ('MD-269', 'Retorno angiológico', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 25),
  ('MD-270', 'Doppler venoso de membros inferiores', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 30);