INSERT INTO catalog_procedures (code, name, category, specialty, type, duration_min) VALUES
  ('MD-271', 'Doppler arterial de membros inferiores', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 30),
  ('MD-272', 'Escleroterapia – varizes fino calibre por sessão', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 60),
  ('MD-273', 'Escleroterapia com microespuma – por sessão', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 60),
  ('MD-274', 'Laser para microvarizes – por sessão', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 60),
  ('MD-275', 'Consulta proctológica', 'Proctologia', 'Proctologia', 'Médico', 40),
  ('MD-276', 'Retorno proctológico', 'Proctologia', 'Proctologia', 'Médico', 20),
  ('MD-277', 'Anuscopia diagnóstica', 'Proctologia', 'Proctologia', 'Médico', 20),
  ('MD-278', 'Retossigmoidoscopia rígida', 'Proctologia', 'Proctologia', 'Médico', 20),
  ('MD-279', 'Ligadura elástica de hemorroidas – por sessão', 'Proctologia', 'Proctologia', 'Médico', 30),
  ('MD-280', 'Infiltração de hemorroidas', 'Proctologia', 'Proctologia', 'Médico', 30),
  ('MD-281', 'Cauterização de lesão perianal', 'Proctologia', 'Proctologia', 'Médico', 30),
  ('MD-282', 'Consulta de mastologia', 'Mastologia', 'Mastologia', 'Médico', 40),
  ('MD-283', 'Retorno mastológico', 'Mastologia', 'Mastologia', 'Médico', 25),
  ('MD-284', 'Exame clínico das mamas', 'Mastologia', 'Mastologia', 'Médico', 20),
  ('MD-285', 'Punção aspirativa de mama PAAF – por lesão', 'Mastologia', 'Mastologia', 'Médico', 30),
  ('MD-286', 'Core biopsy de mama – avaliação e encaminhamento', 'Mastologia', 'Mastologia', 'Médico', 30),
  ('MD-287', 'Consulta geriátrica', 'Geriatria', 'Geriatria', 'Médico', 60),
  ('MD-288', 'Retorno geriátrico', 'Geriatria', 'Geriatria', 'Médico', 30),
  ('MD-289', 'Avaliação geriátrica ampla AGA', 'Geriatria', 'Geriatria', 'Médico', 90),
  ('MD-290', 'Avaliação cognitiva MEEM / MoCA', 'Geriatria', 'Geriatria', 'Médico', 30),
  ('MD-291', 'Avaliação de risco de quedas', 'Geriatria', 'Geriatria', 'Médico', 30),
  ('MD-292', 'Avaliação de fragilidade e sarcopenia', 'Geriatria', 'Geriatria', 'Médico', 45),
  ('MD-293', 'Consulta de medicina do sono', 'Sono', 'Medicina do Sono', 'Médico', 45),
  ('MD-294', 'Retorno medicina do sono', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-295', 'Polissonografia diagnóstica – interpretação', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-296', 'Titulação de CPAP / APAP – ajuste', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-297', 'Actigrafia – avaliação de padrão de sono', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-298', 'Consulta de medicina esportiva', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 45),
  ('MD-299', 'Retorno medicina esportiva', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 25),
  ('MD-300', 'Avaliação de aptidão física e VO2 máximo', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 60),
  ('MD-301', 'Bioimpedância e composição corporal', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 30),
  ('MD-302', 'Prescrição de exercício físico individualizada', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 45),
  ('MD-303', 'Avaliação de lesão esportiva aguda', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 45),
  ('MD-304', 'Consulta de acupuntura', 'Medicina Integrativa', 'Acupuntura', 'Médico', 60),
  ('MD-305', 'Sessão de acupuntura – por sessão', 'Medicina Integrativa', 'Acupuntura', 'Médico', 60),
  ('MD-306', 'Auriculoterapia – por sessão', 'Medicina Integrativa', 'Acupuntura', 'Médico', 30),
  ('MD-307', 'Consulta de medicina integrativa / funcional', 'Medicina Integrativa', 'Medicina Funcional', 'Médico', 60),
  ('MD-308', 'Moxabustão – por sessão', 'Medicina Integrativa', 'Acupuntura', 'Médico', 45),
  ('MD-309', 'Consulta de cirurgia plástica', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-310', 'Retorno pós-operatório – cirurgia plástica', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 30),
  ('MD-311', 'Avaliação pré-cirúrgica completa – plástica', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-312', 'Blefaroplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-313', 'Otoplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 45),
  ('MD-314', 'Rinoplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-315', 'Abdominoplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-316', 'Lipoaspiração – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-317', 'Mamoplastia de aumento – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-318', 'Mamoplastia redutora – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-319', 'Lipofilling facial – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-320', 'Consulta de fonoaudiologia', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-321', 'Retorno fonoaudiológico', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 30),
  ('MD-322', 'Sessão de fonoaudiologia – voz / disfonia', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-323', 'Sessão de fonoaudiologia – deglutição / disfagia', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-324', 'Sessão de fonoaudiologia – linguagem / gagueira', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-325', 'Terapia miofuncional oral', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-326', 'Avaliação fonoaudiológica completa', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 60),
  ('MD-327', 'Consulta de terapia ocupacional', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-328', 'Sessão de terapia ocupacional', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-329', 'Avaliação de independência funcional', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-330', 'Confecção de órtese artesanal', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-331', 'Reabilitação cognitiva – por sessão', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-332', 'Consulta de genética médica', 'Genética', 'Genética Médica', 'Médico', 60),
  ('MD-333', 'Aconselhamento genético', 'Genética', 'Genética Médica', 'Médico', 90),
  ('MD-334', 'Avaliação de malformação congênita', 'Genética', 'Genética Médica', 'Médico', 60),
  ('MD-335', 'Toxina botulínica – região frontal', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-336', 'Toxina botulínica – glabela – linhas do centro', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-337', 'Toxina botulínica – pés de galinha – por lado', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-338', 'Toxina botulínica – pescoço / platisma – Nefertiti', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-339', 'Toxina botulínica – hiperidrose axilar', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-340', 'Toxina botulínica – hiperidrose palmar', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-341', 'Toxina botulínica – hiperidrose plantar', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-342', 'Toxina botulínica – bruxismo / masseter – ambos', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-343', 'Toxina botulínica – sorriso gengival', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-344', 'Toxina botulínica – mento / queixo', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 20),
  ('MD-345', 'Toxina botulínica – nariz – bunny lines', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 20),
  ('MD-346', 'Toxina botulínica – lábios', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 20),
  ('MD-347', 'Toxina botulínica – pacote testa + glabela + pés de galinha', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-348', 'Preenchimento labial com ácido hialurônico', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-349', 'Preenchimento malar com ácido hialurônico', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-350', 'Preenchimento de olheiras – sulco nasojugal', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-351', 'Preenchimento de bigode chinês – sulco nasolabial', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-352', 'Preenchimento de linha mandibular – jawline', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-353', 'Preenchimento de têmpora – região temporal', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-354', 'Preenchimento de lóbulo auricular', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-355', 'Preenchimento de mãos', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-356', 'Rinomodelação não cirúrgica', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-357', 'Bichectomia', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 90),
  ('MD-358', 'Fio de PDO – por região', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-359', 'Bioestimulador de colágeno – Sculptra / Radiesse', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-360', 'Microagulhamento facial com ativo – por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-361', 'Microagulhamento com PRP – por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 90),
  ('MD-362', 'Luz intensa pulsada IPL – por sessão / área', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-363', 'Laser fracionado – resurfacing por sessão / área', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-364', 'Laser Nd:YAG – vasinhos e melasma por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 45),
  ('MD-365', 'Laser CO2 – cicatrizes / lesões por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-366', 'Criolipólise – por alça / aplicador', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 90),
  ('MD-367', 'Radiofrequência facial – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-368', 'Radiofrequência corporal – por sessão / área', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-369', 'Ultrassom microfocado HIFU – facial', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 90),
  ('MD-370', 'Ultrassom microfocado HIFU – corporal', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 90),
  ('MD-371', 'Eletroestimulação muscular EMsculpt – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 30),
  ('MD-372', 'Mesoterapia capilar – por sessão', 'Estética Médica', 'Tricologia', 'Médico', 60),
  ('MD-373', 'Mesoterapia facial – por sessão', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-374', 'Mesoterapia corporal lipolítica – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-375', 'Carboxiterapia facial – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 45),
  ('MD-376', 'Carboxiterapia corporal – gordura localizada por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-377', 'Ozonioterapia injetável – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 45),
  ('MD-378', 'Drenagem linfática manual – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-379', 'Pressoterapia – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 45),
  ('MD-380', 'Endermologia – lipomassagem por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-381', 'PRP plasma rico em plaquetas – facial', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-382', 'PRP plasma rico em plaquetas – capilar', 'Estética Médica', 'Tricologia', 'Médico', 60),
  ('MD-383', 'Sutura simples – por lesão', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-384', 'Sutura com pontos profundos – por plano', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 45),
  ('MD-385', 'Sutura intradérmica', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 45),
  ('MD-386', 'Retirada de pontos', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 15),
  ('MD-387', 'Drenagem de abscesso cutâneo', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-388', 'Desbridamento de ferida', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-389', 'Infiltração com corticosteroide – por lesão', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 20),
  ('MD-390', 'Retirada de corpo estranho superficial', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 20),
  ('MD-391', 'Exérese de cisto sebáceo / epidermoide', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-392', 'Exérese de lipoma', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 45),
  ('MD-393', 'Exérese de fibroma / molusco contagioso', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-394', 'Cauterização química de lesão', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 15),
  ('MD-395', 'Plástica de cicatriz simples – ambulatorial', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 60),
  ('MD-396', 'Curativo simples', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 15),
  ('MD-397', 'Curativo complexo', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 30),
  ('MD-398', 'Flebotomia / coleta de sangue', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-399', 'Aplicação de medicação injetável intramuscular', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-400', 'Aplicação de medicação injetável subcutânea', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-401', 'Aplicação de medicação injetável intravenosa', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-402', 'Infusão venosa – soro ou medicação por hora', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 60),
  ('MD-403', 'Nebulização – por sessão', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-404', 'Aferição de pressão arterial', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-405', 'Oximetria de pulso', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 5),
  ('MD-406', 'Glicemia capilar', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 5),
  ('MD-407', 'ECG técnico de enfermagem', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 15),
  ('MD-408', 'Teste rápido de antígeno covid / gripe / strep', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 15),
  ('MD-409', 'Sondagem nasogástrica', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-410', 'Cateterismo vesical – sondagem vesical', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-411', 'Consulta de dor – algologia', 'Algologia', 'Clínica de Dor', 'Médico', 60),
  ('MD-412', 'Retorno algológico', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-413', 'Bloqueio anestésico diagnóstico', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-414', 'Infiltração de ponto gatilho – trigger point', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-415', 'Bloqueio de faceta articular – por nível', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-416', 'Ozônio intraarticular por articulação', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-417', 'Neuroestimulação transcraniana tDCS – por sessão', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-418', 'Consulta de medicina física e reabilitação', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 60),
  ('MD-419', 'Retorno reabilitação', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 30),
  ('MD-420', 'Avaliação de incapacidade funcional', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 60),
  ('MD-421', 'Reabilitação cardíaca – consulta e programa', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 45),
  ('MD-422', 'Sessão de reabilitação vestibular', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 45),
  ('MD-423', 'Consulta de sexologia', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-424', 'Retorno sexológico', 'Sexologia', 'Sexologia', 'Médico', 45),
  ('MD-425', 'Avaliação de disfunção sexual masculina', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-426', 'Avaliação de disfunção sexual feminina', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-427', 'Terapia sexual – por sessão', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-428', 'Consulta de cirurgia geral', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 40),
  ('MD-429', 'Retorno cirurgia geral', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 25),
  ('MD-430', 'Avaliação cirúrgica de hérnia', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 40),
  ('MD-431', 'Avaliação de colelitíase – vesícula biliar', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 40),
  ('MD-432', 'Consulta de cirurgia bariátrica – avaliação', 'Cirurgia Geral', 'Cirurgia Bariátrica', 'Médico', 60),
  ('MD-433', 'Retorno bariátrico – pós-operatório', 'Cirurgia Geral', 'Cirurgia Bariátrica', 'Médico', 45),
  ('MD-434', 'Check-up executivo – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 120),
  ('MD-435', 'Check-up feminino – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 120),
  ('MD-436', 'Check-up masculino – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 120),
  ('MD-437', 'Check-up pediátrico – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 90),
  ('MD-438', 'Avaliação de risco cardiovascular global', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 45),
  ('MD-439', 'Avaliação de risco oncológico – rastreamento', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 45),
  ('MD-440', 'Programa de cessação do tabagismo – consulta', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 45),
  ('MD-441', 'Aplicação de vacina – dose única', 'Saúde Preventiva', 'Imunização', 'Médico', 10),
  ('MD-442', 'Aplicação de vacina – esquema completo três doses', 'Saúde Preventiva', 'Imunização', 'Médico', 30),
  ('MD-443', 'Consulta de neonatologia', 'Neonatologia', 'Neonatologia', 'Médico', 45),
  ('MD-444', 'Avaliação neonatal precoce – 24 a 72 horas', 'Neonatologia', 'Neonatologia', 'Médico', 45),
  ('MD-445', 'Avaliação de icterícia neonatal', 'Neonatologia', 'Neonatologia', 'Médico', 30),
  ('MD-446', 'Consulta de andrologia', 'Andrologia', 'Andrologia', 'Médico', 45),
  ('MD-447', 'Avaliação de infertilidade masculina', 'Andrologia', 'Andrologia', 'Médico', 60),
  ('MD-448', 'Espermograma – avaliação e interpretação', 'Andrologia', 'Andrologia', 'Médico', 30),
  ('MD-449', 'Consulta de tricologia – queda de cabelo', 'Tricologia', 'Tricologia', 'Médico', 45),
  ('MD-450', 'Fototricograma – mapeamento capilar', 'Tricologia', 'Tricologia', 'Médico', 45),
  ('MD-451', 'Ultrassonografia Abdominal Total', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-452', 'Ultrassonografia Pélvica / Transvaginal', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-453', 'Ultrassonografia de Tireoide', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 20),
  ('MD-454', 'Ultrassonografia Mamária', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-455', 'Mamografia Digital', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-456', 'Densitometria Óssea', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 20),
  ('MD-457', 'Raio-X de Tórax', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 15),
  ('MD-458', 'Raio-X de Extremidades', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 15),
  ('MD-459', 'Ressonância Magnética (RM)', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 45),
  ('MD-460', 'Tomografia Computadorizada (TC) Geral', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('OD-131', 'Consulta de Estomatologia', 'Estomatologia', 'Estomatologia', 'Odontológico', 45),
  ('OD-132', 'Aparelho Ortopédico Funcional dos Maxilares', 'Ortopedia Funcional', 'Ortopedia Funcional dos Maxilares', 'Odontológico', 30),
  ('OD-133', 'Terapia Fotodinâmica (PDT) Odontológica', 'Laserterapia', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-134', 'Consulta para Pacientes com Necessidades Especiais', 'Odontologia Especial', 'Pacientes com Necessidades Especiais', 'Odontológico', 60),
  ('OD-135', 'Consulta em Odontogeriatria', 'Odontogeriatria', 'Odontogeriatria', 'Odontológico', 60);;