-- ===========================================
-- Catálogos globais de sugestão
-- Procedimentos, Insumos e Despesas Fixas
-- ===========================================

CREATE TABLE IF NOT EXISTS catalog_procedures (
  id           SERIAL PRIMARY KEY,
  code         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  category     TEXT,
  specialty    TEXT,
  type         TEXT,
  duration_min INT NOT NULL DEFAULT 30
);

ALTER TABLE catalog_procedures ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog_procedures_read" ON catalog_procedures
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_catalog_proc_name ON catalog_procedures USING gin(to_tsvector('portuguese', name));
CREATE INDEX IF NOT EXISTS idx_catalog_proc_cat  ON catalog_procedures(category);
CREATE INDEX IF NOT EXISTS idx_catalog_proc_spec ON catalog_procedures(specialty);

INSERT INTO catalog_procedures (code, name, category, specialty, type, duration_min) VALUES
  ('OD-001', 'Consulta de avaliação inicial', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 60),
  ('OD-002', 'Consulta de retorno', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-003', 'Exame clínico completo', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 45),
  ('OD-004', 'Planejamento de tratamento', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-005', 'Fotografias clínicas intraorais', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-006', 'Moldagem de estudo – por arcada', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-007', 'Escaneamento digital intraoral', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 30),
  ('OD-008', 'Teste de vitalidade pulpar', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-009', 'Planejamento digital de sorriso (DSD)', 'Avaliação e Diagnóstico', 'Odontologia Geral', 'Odontológico', 60),
  ('OD-010', 'Documentação ortodôntica completa', 'Avaliação e Diagnóstico', 'Ortodontia', 'Odontológico', 60),
  ('OD-011', 'Radiografia periapical – por dente', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 10),
  ('OD-012', 'Radiografia panorâmica', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 15),
  ('OD-013', 'Radiografia interproximal – bite-wing (por par)', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 15),
  ('OD-014', 'Radiografia oclusal', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 10),
  ('OD-015', 'Tomografia computadorizada CBCT – arco completo', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 20),
  ('OD-016', 'Tomografia computadorizada CBCT – região segmentar', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 20),
  ('OD-017', 'Telerradiografia lateral de crânio', 'Radiologia', 'Radiologia Odontológica', 'Odontológico', 15),
  ('OD-018', 'Profilaxia dental – limpeza', 'Prevenção e Profilaxia', 'Odontologia Geral', 'Odontológico', 45),
  ('OD-019', 'Raspagem coronária supragengival', 'Prevenção e Profilaxia', 'Periodontia', 'Odontológico', 60),
  ('OD-020', 'Aplicação tópica de flúor', 'Prevenção e Profilaxia', 'Odontologia Geral', 'Odontológico', 15),
  ('OD-021', 'Selante de fissura – por dente', 'Prevenção e Profilaxia', 'Odontopediatria', 'Odontológico', 20),
  ('OD-022', 'Orientação de higiene oral', 'Prevenção e Profilaxia', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-023', 'Consulta de manutenção periodontal', 'Prevenção e Profilaxia', 'Periodontia', 'Odontológico', 60),
  ('OD-024', 'Aplicação de cariostático IASF – por dente', 'Prevenção e Profilaxia', 'Odontopediatria', 'Odontológico', 10),
  ('OD-025', 'Raspagem e alisamento radicular – por sextante', 'Periodontia', 'Periodontia', 'Odontológico', 60),
  ('OD-026', 'Curetagem subgengival – por sextante', 'Periodontia', 'Periodontia', 'Odontológico', 60),
  ('OD-027', 'Gengivectomia / gengivoplastia', 'Periodontia', 'Periodontia', 'Odontológico', 90),
  ('OD-028', 'Cirurgia periodontal a retalho – por sextante', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-029', 'Enxerto gengival livre', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-030', 'Enxerto de tecido conjuntivo subepitelial', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-031', 'Cirurgia de aumento de coroa clínica – por dente', 'Periodontia', 'Periodontia', 'Odontológico', 90),
  ('OD-032', 'Frenectomia labial / lingual', 'Periodontia', 'Cirurgia Oral', 'Odontológico', 60),
  ('OD-033', 'Recobrimento radicular – por dente', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-034', 'Regeneração óssea guiada', 'Periodontia', 'Periodontia', 'Odontológico', 120),
  ('OD-035', 'Restauração resina composta classe I – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-036', 'Restauração resina composta classe II – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-037', 'Restauração resina composta classe III – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-038', 'Restauração resina composta classe IV – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-039', 'Restauração resina composta classe V – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 30),
  ('OD-040', 'Restauração amálgama classe I', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-041', 'Restauração amálgama classe II', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-042', 'Troca / substituição de restauração', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-043', 'Cimentação de pino intracanal – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 45),
  ('OD-044', 'Núcleo de preenchimento – por dente', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 60),
  ('OD-045', 'Onlay em resina composta', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 90),
  ('OD-046', 'Inlay em resina composta', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 90),
  ('OD-047', 'Overlay em resina composta', 'Dentística', 'Odontologia Restauradora', 'Odontológico', 90),
  ('OD-048', 'Tratamento endodôntico – dente unirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 90),
  ('OD-049', 'Tratamento endodôntico – dente birradicular', 'Endodontia', 'Endodontia', 'Odontológico', 120),
  ('OD-050', 'Tratamento endodôntico – dente multirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 150),
  ('OD-051', 'Retratamento endodôntico – dente unirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 120),
  ('OD-052', 'Retratamento endodôntico – dente birradicular', 'Endodontia', 'Endodontia', 'Odontológico', 150),
  ('OD-053', 'Retratamento endodôntico – dente multirradicular', 'Endodontia', 'Endodontia', 'Odontológico', 180),
  ('OD-054', 'Apicectomia – por dente', 'Endodontia', 'Endodontia', 'Odontológico', 120),
  ('OD-055', 'Capeamento pulpar direto', 'Endodontia', 'Endodontia', 'Odontológico', 60),
  ('OD-056', 'Capeamento pulpar indireto', 'Endodontia', 'Endodontia', 'Odontológico', 45),
  ('OD-057', 'Pulpotomia', 'Endodontia', 'Endodontia', 'Odontológico', 60),
  ('OD-058', 'Biopulpectomia', 'Endodontia', 'Endodontia', 'Odontológico', 90),
  ('OD-059', 'Necropulpectomia', 'Endodontia', 'Endodontia', 'Odontológico', 90),
  ('OD-060', 'Medicação intracanal – curativo por sessão', 'Endodontia', 'Endodontia', 'Odontológico', 30),
  ('OD-061', 'Exodontia de dente permanente', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 45),
  ('OD-062', 'Exodontia de dente decíduo', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 30),
  ('OD-063', 'Exodontia de dente semi-incluso', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 90),
  ('OD-064', 'Exodontia de siso incluso – dente do juízo', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 120),
  ('OD-065', 'Alveoloplastia – por região', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 60),
  ('OD-066', 'Excisão de cisto odontogênico', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 90),
  ('OD-067', 'Biópsia de tecido mole oral', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 45),
  ('OD-068', 'Reimplante dental', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 90),
  ('OD-069', 'Levantamento de seio maxilar – sinus lift', 'Cirurgia Oral', 'Implantodontia', 'Odontológico', 180),
  ('OD-070', 'Enxerto ósseo em bloco', 'Cirurgia Oral', 'Implantodontia', 'Odontológico', 180),
  ('OD-071', 'Enxerto ósseo particulado', 'Cirurgia Oral', 'Implantodontia', 'Odontológico', 120),
  ('OD-072', 'Instalação de implante osseointegrado – por implante', 'Implantodontia', 'Implantodontia', 'Odontológico', 120),
  ('OD-073', 'Reabertura de implante – 2ª fase cirúrgica', 'Implantodontia', 'Implantodontia', 'Odontológico', 45),
  ('OD-074', 'Instalação de cicatrizador gengival – por implante', 'Implantodontia', 'Implantodontia', 'Odontológico', 30),
  ('OD-075', 'Moldagem para prótese sobre implante', 'Implantodontia', 'Implantodontia', 'Odontológico', 45),
  ('OD-076', 'Coroa sobre implante – unitária', 'Implantodontia', 'Implantodontia', 'Odontológico', 60),
  ('OD-077', 'Protocolo fixo sobre implantes – por arco', 'Implantodontia', 'Implantodontia', 'Odontológico', 120),
  ('OD-078', 'Overdenture sobre implantes – por arco', 'Implantodontia', 'Implantodontia', 'Odontológico', 90),
  ('OD-079', 'Implante carga imediata – unitário', 'Implantodontia', 'Implantodontia', 'Odontológico', 150),
  ('OD-080', 'Remoção de implante osseointegrado', 'Implantodontia', 'Implantodontia', 'Odontológico', 90),
  ('OD-081', 'Coroa metalocerâmica – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-082', 'Coroa total cerâmica e-max – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-083', 'Coroa total zircônia – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-084', 'Coroa provisória – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 45),
  ('OD-085', 'Faceta de porcelana – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-086', 'Faceta de resina direta – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-087', 'Inlay cerâmico – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-088', 'Onlay cerâmico – por dente', 'Prótese', 'Prótese Dentária', 'Odontológico', 90),
  ('OD-089', 'Prótese parcial removível PPR – por arco', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-090', 'Prótese total convencional – por arco', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-091', 'Prótese parcial fixa – por elemento ponteado', 'Prótese', 'Prótese Dentária', 'Odontológico', 60),
  ('OD-092', 'Reembasamento de prótese', 'Prótese', 'Prótese Dentária', 'Odontológico', 45),
  ('OD-093', 'Reparação / conserto de prótese', 'Prótese', 'Prótese Dentária', 'Odontológico', 30),
  ('OD-094', 'Cimentação de prótese fixa', 'Prótese', 'Prótese Dentária', 'Odontológico', 45),
  ('OD-095', 'Instalação de aparelho fixo metálico – arco completo', 'Ortodontia', 'Ortodontia', 'Odontológico', 90),
  ('OD-096', 'Instalação de aparelho fixo estético cerâmico / safira', 'Ortodontia', 'Ortodontia', 'Odontológico', 90),
  ('OD-097', 'Instalação de alinhadores invisíveis – arco completo', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-098', 'Manutenção mensal de aparelho fixo', 'Ortodontia', 'Ortodontia', 'Odontológico', 30),
  ('OD-099', 'Instalação de aparelho ortopédico funcional', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-100', 'Contenção removível – por arco', 'Ortodontia', 'Ortodontia', 'Odontológico', 30),
  ('OD-101', 'Contenção fixa colada', 'Ortodontia', 'Ortodontia', 'Odontológico', 45),
  ('OD-102', 'Expansor de palato RPE', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-103', 'Distalizador de molar', 'Ortodontia', 'Ortodontia', 'Odontológico', 60),
  ('OD-104', 'Remoção de aparelho fixo', 'Ortodontia', 'Ortodontia', 'Odontológico', 45),
  ('OD-105', 'Placa de mordida / placa de bruxismo ortodôntica', 'Ortodontia', 'Ortodontia', 'Odontológico', 45),
  ('OD-106', 'Consulta de avaliação infantil', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 45),
  ('OD-107', 'Restauração em resina composta – dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 45),
  ('OD-108', 'Coroa de aço inoxidável – por dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 60),
  ('OD-109', 'Pulpotomia em dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 60),
  ('OD-110', 'Pulpectomia em dente decíduo', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 90),
  ('OD-111', 'Aparelho para manutenção de espaço', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 60),
  ('OD-112', 'Orientação de hábitos bucais', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 30),
  ('OD-113', 'Tratamento restaurador atraumático ART', 'Odontopediatria', 'Odontopediatria', 'Odontológico', 30),
  ('OD-114', 'Clareamento dental de consultório – por sessão', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-115', 'Clareamento dental caseiro – moldeira + gel', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 45),
  ('OD-116', 'Clareamento dental combinado consultório + caseiro', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-117', 'Microabrasão do esmalte – por dente', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 30),
  ('OD-118', 'Fechamento de diastema em resina direta', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-119', 'Remodelação estética com resina – por dente', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 90),
  ('OD-120', 'Planejamento digital do sorriso', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 60),
  ('OD-121', 'Placa miorrelaxante bruxismo termoformada', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 45),
  ('OD-122', 'Placa miorrelaxante rígida usinada / fresada', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 45),
  ('OD-123', 'Placa de avanço mandibular – ronco / apneia', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 45),
  ('OD-124', 'Ajuste oclusal / desgaste seletivo', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 60),
  ('OD-125', 'Tratamento de disfunção temporomandibular DTM', 'Disfunção Temporomandibular', 'Oclusão e DTM', 'Odontológico', 60),
  ('OD-126', 'Toxina botulínica bruxismo masseter – por lado', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 30),
  ('OD-127', 'Ácido hialurônico labial – harmonização dental', 'Estética Dental', 'Odontologia Estética', 'Odontológico', 45),
  ('OD-128', 'Sutura de tecido oral', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 30),
  ('OD-129', 'Retirada de pontos orais', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 15),
  ('OD-130', 'Drenagem de abscesso dentoalveolar', 'Cirurgia Oral', 'Cirurgia Oral', 'Odontológico', 45),
  ('MD-001', 'Consulta clínica geral', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 30),
  ('MD-002', 'Consulta de retorno clínico', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 20),
  ('MD-003', 'Consulta de urgência / pronto atendimento', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 30),
  ('MD-004', 'Avaliação pré-operatória', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 45),
  ('MD-005', 'Avaliação admissional – medicina do trabalho', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-006', 'Avaliação periódica – medicina do trabalho', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-007', 'Avaliação de retorno ao trabalho', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-008', 'Avaliação para mudança de função', 'Consultas e Avaliações', 'Medicina do Trabalho', 'Médico', 30),
  ('MD-009', 'Atestado médico', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-010', 'Declaração médica', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-011', 'Receita médica – emissão', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-012', 'Solicitação de exames laboratoriais', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 10),
  ('MD-013', 'Avaliação pré-anestésica', 'Consultas e Avaliações', 'Anestesiologia', 'Médico', 45),
  ('MD-014', 'Segunda opinião médica', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 60),
  ('MD-015', 'Teleconsulta / consulta online', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 30),
  ('MD-016', 'Consulta domiciliar', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 60),
  ('MD-017', 'Consulta de medicina preventiva – check-up', 'Consultas e Avaliações', 'Clínica Geral', 'Médico', 60),
  ('MD-018', 'Consulta cardiológica', 'Cardiologia', 'Cardiologia', 'Médico', 45),
  ('MD-019', 'Retorno cardiológico', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-020', 'Eletrocardiograma ECG', 'Cardiologia', 'Cardiologia', 'Médico', 15),
  ('MD-021', 'Ecocardiograma transtorácico', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-022', 'Ecocardiograma transesofágico', 'Cardiologia', 'Cardiologia', 'Médico', 90),
  ('MD-023', 'Ecocardiograma de estresse com dobutamina', 'Cardiologia', 'Cardiologia', 'Médico', 90),
  ('MD-024', 'Teste ergométrico – esteira', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-025', 'Holter 24 horas – instalação + interpretação', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-026', 'Holter 7 dias', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-027', 'MAPA – monitorização ambulatorial da pressão arterial', 'Cardiologia', 'Cardiologia', 'Médico', 20),
  ('MD-028', 'Teste de mesa inclinada – tilt test', 'Cardiologia', 'Cardiologia', 'Médico', 90),
  ('MD-029', 'Cardioversão elétrica eletiva', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-030', 'Avaliação de marca-passo implantado', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-031', 'Angiotomografia coronariana', 'Cardiologia', 'Cardiologia', 'Médico', 60),
  ('MD-032', 'Score de cálcio coronariano', 'Cardiologia', 'Cardiologia', 'Médico', 30),
  ('MD-033', 'Avaliação de insuficiência cardíaca', 'Cardiologia', 'Cardiologia', 'Médico', 45),
  ('MD-034', 'Consulta de hipertensão arterial sistêmica', 'Cardiologia', 'Cardiologia', 'Médico', 40),
  ('MD-035', 'Consulta dermatológica', 'Dermatologia', 'Dermatologia', 'Médico', 40),
  ('MD-036', 'Retorno dermatológico', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-037', 'Dermatoscopia – por lesão', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-038', 'Mapeamento corporal – dermatoscopia digital', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-039', 'Biópsia de pele punch', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-040', 'Biópsia excisional de pele', 'Dermatologia', 'Dermatologia', 'Médico', 45),
  ('MD-041', 'Criocirurgia – crioterapia por lesão', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-042', 'Eletrocauterização por lesão', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-043', 'Excisão de lesão cutânea benigna', 'Dermatologia', 'Dermatologia', 'Médico', 45),
  ('MD-044', 'Excisão de lesão cutânea maligna com margem', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-045', 'Curetagem de lesão cutânea', 'Dermatologia', 'Dermatologia', 'Médico', 20),
  ('MD-046', 'Peeling químico superficial AHA / BHA', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-047', 'Peeling químico médio TCA', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-048', 'Peeling químico profundo – fenol', 'Dermatologia', 'Dermatologia', 'Médico', 120),
  ('MD-049', 'Laser ablativo por sessão / região', 'Dermatologia', 'Dermatologia', 'Médico', 90),
  ('MD-050', 'Laser não ablativo por sessão / região', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-051', 'Fototerapia UVB narrowband – por sessão', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-052', 'PUVA terapia – por sessão', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-053', 'Excisão de unha / onicogrifose', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-054', 'Plástica ungueal – unha encravada', 'Dermatologia', 'Dermatologia', 'Médico', 30),
  ('MD-055', 'Microagulhamento clínico – por sessão', 'Dermatologia', 'Dermatologia', 'Médico', 60),
  ('MD-056', 'Consulta ginecológica', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 40),
  ('MD-057', 'Retorno ginecológico', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 25),
  ('MD-058', 'Consulta de pré-natal – 1º trimestre', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 45),
  ('MD-059', 'Consulta de pré-natal – 2º trimestre', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 40),
  ('MD-060', 'Consulta de pré-natal – 3º trimestre', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 40),
  ('MD-061', 'Consulta puerperal – pós-parto', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Médico', 40),
  ('MD-062', 'Coleta de Papanicolau – colpocitologia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-063', 'Colposcopia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-064', 'Biópsia de colo uterino – punch', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-065', 'LEEP – conização com alça diatérmica', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 60),
  ('MD-066', 'Inserção de DIU', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-067', 'Remoção de DIU', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-068', 'Inserção de implante anticoncepcional subdérmico', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-069', 'Remoção de implante anticoncepcional subdérmico', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 20),
  ('MD-070', 'Histeroscopia diagnóstica', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 45),
  ('MD-071', 'Histeroscopia cirúrgica – polipectomia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 60),
  ('MD-072', 'Vulvoscopia', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-073', 'Biópsia de vulva', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 30),
  ('MD-074', 'Consulta de climatério / menopausa', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 45),
  ('MD-075', 'Avaliação de disfunção sexual feminina', 'Ginecologia e Obstetrícia', 'Ginecologia', 'Médico', 45),
  ('MD-076', 'Consulta pediátrica geral', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-077', 'Retorno pediátrico', 'Pediatria', 'Pediatria', 'Médico', 25),
  ('MD-078', 'Puericultura – neonato 0 a 28 dias', 'Pediatria', 'Pediatria', 'Médico', 45),
  ('MD-079', 'Puericultura – lactente 1 a 6 meses', 'Pediatria', 'Pediatria', 'Médico', 45),
  ('MD-080', 'Puericultura – lactente 6 a 12 meses', 'Pediatria', 'Pediatria', 'Médico', 45),
  ('MD-081', 'Puericultura – criança 1 a 4 anos', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-082', 'Puericultura – criança 5 a 10 anos', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-083', 'Consulta do adolescente 11 a 19 anos', 'Pediatria', 'Pediatria', 'Médico', 40),
  ('MD-084', 'Avaliação do desenvolvimento neuropsicomotor', 'Pediatria', 'Pediatria', 'Médico', 60),
  ('MD-085', 'Triagem auditiva neonatal – EOA', 'Pediatria', 'Pediatria', 'Médico', 20),
  ('MD-086', 'Triagem visual neonatal – teste do olhinho', 'Pediatria', 'Pediatria', 'Médico', 15),
  ('MD-087', 'Teste do pezinho ampliado', 'Pediatria', 'Pediatria', 'Médico', 15),
  ('MD-088', 'Vacinação – por dose', 'Pediatria', 'Pediatria', 'Médico', 10),
  ('MD-089', 'Avaliação de crescimento e peso', 'Pediatria', 'Pediatria', 'Médico', 20),
  ('MD-090', 'Teste SNAP-IV – avaliação de TDAH', 'Pediatria', 'Pediatria', 'Médico', 30),
  ('MD-091', 'Consulta ortopédica', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 40),
  ('MD-092', 'Retorno ortopédico', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-093', 'Imobilização gessada – por segmento', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-094', 'Retirada de gesso', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 15),
  ('MD-095', 'Artrocentese – joelho', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-096', 'Artrocentese – ombro', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-097', 'Artrocentese – tornozelo', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-098', 'Infiltração articular com corticosteroide – joelho', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-099', 'Infiltração articular com ácido hialurônico – joelho', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-100', 'Infiltração periarticular – tendão / bursa', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-101', 'Bloqueio nervoso periférico', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-102', 'Redução de fratura sem fixação', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 60),
  ('MD-103', 'Aplicação de órtese / imobilizador – por segmento', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 20),
  ('MD-104', 'Avaliação de força muscular e amplitude articular', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 30),
  ('MD-105', 'Avaliação pré-cirúrgica ortopédica', 'Ortopedia', 'Ortopedia e Traumatologia', 'Médico', 45),
  ('MD-106', 'Avaliação fisioterapêutica', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-107', 'Sessão de fisioterapia ortopédica / musculoesquelética', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-108', 'Sessão de fisioterapia neurológica', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-109', 'Sessão de RPG – reeducação postural global', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-110', 'Sessão de pilates clínico individual', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-111', 'Dry needling – agulhamento a seco – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 45),
  ('MD-112', 'Ultrassom terapêutico – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-113', 'TENS – eletroestimulação nervosa transcutânea', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-114', 'FES – estimulação elétrica funcional', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-115', 'Liberação miofascial – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-116', 'Terapia manual / mobilização articular', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-117', 'Fisioterapia respiratória – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 45),
  ('MD-118', 'Fisioterapia pélvica / uroginecológica – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-119', 'Hidroterapia / cinesioterapia aquática – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 60),
  ('MD-120', 'Ventosaterapia – cupping', 'Fisioterapia', 'Fisioterapia', 'Médico', 45),
  ('MD-121', 'Kinesio taping – aplicação por região', 'Fisioterapia', 'Fisioterapia', 'Médico', 20),
  ('MD-122', 'Tração cervical / lombar – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-123', 'Laser de baixa intensidade LLLT – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-124', 'Ondas de choque extracorpórea – por sessão', 'Fisioterapia', 'Fisioterapia', 'Médico', 30),
  ('MD-125', 'Consulta neurológica', 'Neurologia', 'Neurologia', 'Médico', 45),
  ('MD-126', 'Retorno neurológico', 'Neurologia', 'Neurologia', 'Médico', 30),
  ('MD-127', 'Eletroencefalograma EEG', 'Neurologia', 'Neurologia', 'Médico', 60),
  ('MD-128', 'EEG com privação do sono', 'Neurologia', 'Neurologia', 'Médico', 90),
  ('MD-129', 'Eletroneuromiografia ENMG', 'Neurologia', 'Neurologia', 'Médico', 90),
  ('MD-130', 'Velocidade de condução nervosa – VCN', 'Neurologia', 'Neurologia', 'Médico', 60),
  ('MD-131', 'Avaliação neuropsicológica', 'Neurologia', 'Neurologia', 'Médico', 120),
  ('MD-132', 'Avaliação de tontura e equilíbrio – otoneurologia', 'Neurologia', 'Neurologia', 'Médico', 60),
  ('MD-133', 'Avaliação e tratamento de cefaleia – enxaqueca', 'Neurologia', 'Neurologia', 'Médico', 45),
  ('MD-134', 'Toxina botulínica para enxaqueca crônica', 'Neurologia', 'Neurologia', 'Médico', 45),
  ('MD-135', 'Consulta endocrinológica', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-136', 'Retorno endocrinológico', 'Endocrinologia', 'Endocrinologia', 'Médico', 30),
  ('MD-137', 'Avaliação e controle de diabetes tipo 1', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-138', 'Avaliação e controle de diabetes tipo 2', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-139', 'Avaliação e tratamento de hipotireoidismo', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-140', 'Avaliação e tratamento de hipertireoidismo', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-141', 'Avaliação e tratamento de dislipidemia', 'Endocrinologia', 'Endocrinologia', 'Médico', 30),
  ('MD-142', 'Avaliação de obesidade e sobrepeso', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-143', 'Avaliação de osteoporose e osteopenia', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-144', 'Avaliação hormonal masculina / TRT', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-145', 'Consulta de síndrome metabólica', 'Endocrinologia', 'Endocrinologia', 'Médico', 45),
  ('MD-146', 'Consulta oftalmológica', 'Oftalmologia', 'Oftalmologia', 'Médico', 40),
  ('MD-147', 'Retorno oftalmológico', 'Oftalmologia', 'Oftalmologia', 'Médico', 20),
  ('MD-148', 'Refração / prescrição de óculos', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-149', 'Tonometria de aplanação', 'Oftalmologia', 'Oftalmologia', 'Médico', 15),
  ('MD-150', 'Mapeamento de retina', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-151', 'Retinografia colorida', 'Oftalmologia', 'Oftalmologia', 'Médico', 20),
  ('MD-152', 'OCT – tomografia de coerência óptica', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-153', 'Campimetria / perimetria computadorizada', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-154', 'Paquimetria corneal', 'Oftalmologia', 'Oftalmologia', 'Médico', 15),
  ('MD-155', 'Topografia corneal', 'Oftalmologia', 'Oftalmologia', 'Médico', 20),
  ('MD-156', 'Adaptação de lentes de contato', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-157', 'Aplicação de laser na retina – por sessão', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-158', 'Injeção intravítrea – por olho', 'Oftalmologia', 'Oftalmologia', 'Médico', 30),
  ('MD-159', 'Avaliação e tratamento de estrabismo', 'Oftalmologia', 'Oftalmologia', 'Médico', 45),
  ('MD-160', 'Consulta ORL – otorrinolaringológica', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 40),
  ('MD-161', 'Retorno ORL', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-162', 'Audiometria tonal liminar', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-163', 'Audiometria vocal – logoaudiometria', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-164', 'Imitanciometria – timpanometria', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-165', 'Pesquisa do reflexo estapediano', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 15),
  ('MD-166', 'Laringoscopia direta / videolaringoscopia', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-167', 'Nasofibroscopia', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-168', 'Lavagem auricular / ceruminolítico', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 20),
  ('MD-169', 'Punção de seio paranasal – sinusite', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-170', 'Manobra de Epley – VPPB', 'Otorrinolaringologia', 'Otorrinolaringologia', 'Médico', 30),
  ('MD-171', 'Consulta psiquiátrica', 'Psiquiatria', 'Psiquiatria', 'Médico', 60),
  ('MD-172', 'Retorno psiquiátrico', 'Psiquiatria', 'Psiquiatria', 'Médico', 30),
  ('MD-173', 'Avaliação psiquiátrica diagnóstica completa', 'Psiquiatria', 'Psiquiatria', 'Médico', 90),
  ('MD-174', 'Avaliação psiquiátrica pericial / forense', 'Psiquiatria', 'Psiquiatria', 'Médico', 120),
  ('MD-175', 'Psicoterapia individual – médico – por sessão', 'Psiquiatria', 'Psiquiatria', 'Médico', 50),
  ('MD-176', 'Psicoterapia individual – psicólogo – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-177', 'Terapia cognitivo-comportamental TCC – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-178', 'EMDR – por sessão', 'Psicologia', 'Psicologia', 'Médico', 60),
  ('MD-179', 'Avaliação psicológica – laudo completo', 'Psicologia', 'Psicologia', 'Médico', 120),
  ('MD-180', 'Psicoterapia de casal – por sessão', 'Psicologia', 'Psicologia', 'Médico', 60),
  ('MD-181', 'Psicoterapia familiar – por sessão', 'Psicologia', 'Psicologia', 'Médico', 60),
  ('MD-182', 'Terapia de aceitação e compromisso ACT – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-183', 'Terapia dialética comportamental DBT – por sessão', 'Psicologia', 'Psicologia', 'Médico', 50),
  ('MD-184', 'Avaliação neuropsicológica – laudo', 'Psicologia', 'Neuropsicologia', 'Médico', 180),
  ('MD-185', 'Consulta urológica', 'Urologia', 'Urologia', 'Médico', 40),
  ('MD-186', 'Retorno urológico', 'Urologia', 'Urologia', 'Médico', 20),
  ('MD-187', 'Urofluxometria', 'Urologia', 'Urologia', 'Médico', 30),
  ('MD-188', 'Urodinâmica completa', 'Urologia', 'Urologia', 'Médico', 60),
  ('MD-189', 'Cistoscopia diagnóstica', 'Urologia', 'Urologia', 'Médico', 30),
  ('MD-190', 'Calibração uretral', 'Urologia', 'Urologia', 'Médico', 20),
  ('MD-191', 'Vasectomia – procedimento ambulatorial', 'Urologia', 'Urologia', 'Médico', 60),
  ('MD-192', 'Biópsia de próstata transretal – avaliação', 'Urologia', 'Urologia', 'Médico', 30),
  ('MD-193', 'Avaliação de disfunção erétil', 'Urologia', 'Urologia', 'Médico', 45),
  ('MD-194', 'Avaliação de infertilidade masculina', 'Urologia', 'Urologia', 'Médico', 45),
  ('MD-195', 'Consulta gastroenterológica', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 40),
  ('MD-196', 'Retorno gastroenterológico', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 25),
  ('MD-197', 'Endoscopia digestiva alta EDA', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-198', 'Colonoscopia', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 60),
  ('MD-199', 'Retossigmoidoscopia flexível', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-200', 'Biópsia endoscópica', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-201', 'Teste respiratório para H. pylori', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-202', 'Manometria esofágica de alta resolução', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 60),
  ('MD-203', 'pHmetria esofágica 24h – interpretação', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 30),
  ('MD-204', 'Avaliação de doença inflamatória intestinal', 'Gastroenterologia', 'Gastroenterologia', 'Médico', 45),
  ('MD-205', 'Consulta nutricional', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-206', 'Retorno nutricional', 'Nutrição', 'Nutrição', 'Médico', 30),
  ('MD-207', 'Avaliação antropométrica completa', 'Nutrição', 'Nutrição', 'Médico', 45),
  ('MD-208', 'Plano alimentar personalizado', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-209', 'Avaliação nutricional para esportistas', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-210', 'Avaliação nutricional pediátrica', 'Nutrição', 'Nutrição', 'Médico', 60),
  ('MD-211', 'Consulta de nutrologia', 'Nutrologia', 'Nutrologia', 'Médico', 45),
  ('MD-212', 'Retorno nutrológico', 'Nutrologia', 'Nutrologia', 'Médico', 30),
  ('MD-213', 'Avaliação de composição corporal – bioimpedância', 'Nutrologia', 'Nutrologia', 'Médico', 30),
  ('MD-214', 'Avaliação para reeducação alimentar', 'Nutrologia', 'Nutrologia', 'Médico', 45),
  ('MD-215', 'Protocolo de emagrecimento supervisionado', 'Nutrologia', 'Nutrologia', 'Médico', 60),
  ('MD-216', 'Consulta reumatológica', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-217', 'Retorno reumatológico', 'Reumatologia', 'Reumatologia', 'Médico', 30),
  ('MD-218', 'Avaliação de artrite reumatoide', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-219', 'Avaliação de lúpus eritematoso sistêmico', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-220', 'Avaliação de espondiloartrite / espondilite anquilosante', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-221', 'Avaliação de fibromialgia', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-222', 'Avaliação e tratamento de gota', 'Reumatologia', 'Reumatologia', 'Médico', 30),
  ('MD-223', 'Avaliação de síndrome de Sjögren', 'Reumatologia', 'Reumatologia', 'Médico', 45),
  ('MD-224', 'Infiltração articular reumatológica – por articulação', 'Reumatologia', 'Reumatologia', 'Médico', 30),
  ('MD-225', 'Consulta pneumológica', 'Pneumologia', 'Pneumologia', 'Médico', 40),
  ('MD-226', 'Retorno pneumológico', 'Pneumologia', 'Pneumologia', 'Médico', 25),
  ('MD-227', 'Espirometria com broncodilatador', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-228', 'Espirometria simples', 'Pneumologia', 'Pneumologia', 'Médico', 30),
  ('MD-229', 'Pico de fluxo expiratório – peak flow', 'Pneumologia', 'Pneumologia', 'Médico', 15),
  ('MD-230', 'Teste de caminhada de 6 minutos', 'Pneumologia', 'Pneumologia', 'Médico', 30),
  ('MD-231', 'Oximetria noturna', 'Pneumologia', 'Pneumologia', 'Médico', 20),
  ('MD-232', 'Avaliação de asma grave', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-233', 'Avaliação e tratamento de DPOC', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-234', 'Avaliação de apneia obstrutiva do sono', 'Pneumologia', 'Pneumologia', 'Médico', 45),
  ('MD-235', 'Consulta infectológica', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-236', 'Retorno infectológico', 'Infectologia', 'Infectologia', 'Médico', 30),
  ('MD-237', 'Avaliação e tratamento de HIV / AIDS', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-238', 'Avaliação de hepatites virais B e C', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-239', 'Avaliação pós-exposição a material biológico', 'Infectologia', 'Infectologia', 'Médico', 30),
  ('MD-240', 'Consulta de medicina de viagem', 'Infectologia', 'Infectologia', 'Médico', 45),
  ('MD-241', 'Consulta imunológica / alergológica', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 45),
  ('MD-242', 'Retorno alergia / imunologia', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 30),
  ('MD-243', 'Teste de alergia – prick test por bateria', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 60),
  ('MD-244', 'Teste de contato – patch test', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 60),
  ('MD-245', 'Teste de provocação oral – alimento / medicamento', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 120),
  ('MD-246', 'Imunoterapia – vacina alergênica por sessão', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 20),
  ('MD-247', 'Avaliação de imunodeficiência primária', 'Alergologia', 'Alergologia e Imunologia', 'Médico', 60),
  ('MD-248', 'Consulta nefrológica', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-249', 'Retorno nefrológico', 'Nefrologia', 'Nefrologia', 'Médico', 30),
  ('MD-250', 'Avaliação de doença renal crônica', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-251', 'Avaliação de hipertensão arterial resistente', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-252', 'Avaliação de nefrolitíase – cálculo renal', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-253', 'Avaliação de glomerulonefrite', 'Nefrologia', 'Nefrologia', 'Médico', 45),
  ('MD-254', 'Consulta hepatológica', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-255', 'Retorno hepatológico', 'Hepatologia', 'Hepatologia', 'Médico', 30),
  ('MD-256', 'Avaliação de esteatose hepática – gordura no fígado', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-257', 'Avaliação de cirrose hepática', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-258', 'Avaliação de hepatite autoimune', 'Hepatologia', 'Hepatologia', 'Médico', 45),
  ('MD-259', 'Consulta hematológica', 'Hematologia', 'Hematologia', 'Médico', 45),
  ('MD-260', 'Retorno hematológico', 'Hematologia', 'Hematologia', 'Médico', 30),
  ('MD-261', 'Avaliação de anemia', 'Hematologia', 'Hematologia', 'Médico', 30),
  ('MD-262', 'Avaliação de coagulopatia / distúrbio hemorrágico', 'Hematologia', 'Hematologia', 'Médico', 45),
  ('MD-263', 'Avaliação de trombofilia', 'Hematologia', 'Hematologia', 'Médico', 45),
  ('MD-264', 'Consulta oncológica – avaliação diagnóstica', 'Oncologia', 'Oncologia Clínica', 'Médico', 60),
  ('MD-265', 'Retorno oncológico', 'Oncologia', 'Oncologia Clínica', 'Médico', 45),
  ('MD-266', 'Avaliação de resposta ao tratamento oncológico', 'Oncologia', 'Oncologia Clínica', 'Médico', 60),
  ('MD-267', 'Consulta de cuidados paliativos', 'Oncologia', 'Cuidados Paliativos', 'Médico', 60),
  ('MD-268', 'Consulta de angiologia / cirurgia vascular', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 40),
  ('MD-269', 'Retorno angiológico', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 25),
  ('MD-270', 'Doppler venoso de membros inferiores', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 30),
  ('MD-271', 'Doppler arterial de membros inferiores', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 30),
  ('MD-272', 'Escleroterapia – varizes fino calibre por sessão', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 60),
  ('MD-273', 'Escleroterapia com microespuma – por sessão', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 60),
  ('MD-274', 'Laser para microvarizes – por sessão', 'Angiologia', 'Angiologia e Cirurgia Vascular', 'Médico', 60),
  ('MD-275', 'Consulta proctológica', 'Proctologia', 'Proctologia', 'Médico', 40),
  ('MD-276', 'Retorno proctológico', 'Proctologia', 'Proctologia', 'Médico', 20),
  ('MD-277', 'Anuscopia diagnóstica', 'Proctologia', 'Proctologia', 'Médico', 20),
  ('MD-278', 'Retossigmoidoscopia rígida', 'Proctologia', 'Proctologia', 'Médico', 20),
  ('MD-279', 'Ligadura elástica de hemorroidas – por sessão', 'Proctologia', 'Proctologia', 'Médico', 30),
  ('MD-280', 'Infiltração de hemorroidas', 'Proctologia', 'Proctologia', 'Médico', 30),
  ('MD-281', 'Cauterização de lesão perianal', 'Proctologia', 'Proctologia', 'Médico', 30),
  ('MD-282', 'Consulta de mastologia', 'Mastologia', 'Mastologia', 'Médico', 40),
  ('MD-283', 'Retorno mastológico', 'Mastologia', 'Mastologia', 'Médico', 25),
  ('MD-284', 'Exame clínico das mamas', 'Mastologia', 'Mastologia', 'Médico', 20),
  ('MD-285', 'Punção aspirativa de mama PAAF – por lesão', 'Mastologia', 'Mastologia', 'Médico', 30),
  ('MD-286', 'Core biopsy de mama – avaliação e encaminhamento', 'Mastologia', 'Mastologia', 'Médico', 30),
  ('MD-287', 'Consulta geriátrica', 'Geriatria', 'Geriatria', 'Médico', 60),
  ('MD-288', 'Retorno geriátrico', 'Geriatria', 'Geriatria', 'Médico', 30),
  ('MD-289', 'Avaliação geriátrica ampla AGA', 'Geriatria', 'Geriatria', 'Médico', 90),
  ('MD-290', 'Avaliação cognitiva MEEM / MoCA', 'Geriatria', 'Geriatria', 'Médico', 30),
  ('MD-291', 'Avaliação de risco de quedas', 'Geriatria', 'Geriatria', 'Médico', 30),
  ('MD-292', 'Avaliação de fragilidade e sarcopenia', 'Geriatria', 'Geriatria', 'Médico', 45),
  ('MD-293', 'Consulta de medicina do sono', 'Sono', 'Medicina do Sono', 'Médico', 45),
  ('MD-294', 'Retorno medicina do sono', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-295', 'Polissonografia diagnóstica – interpretação', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-296', 'Titulação de CPAP / APAP – ajuste', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-297', 'Actigrafia – avaliação de padrão de sono', 'Sono', 'Medicina do Sono', 'Médico', 30),
  ('MD-298', 'Consulta de medicina esportiva', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 45),
  ('MD-299', 'Retorno medicina esportiva', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 25),
  ('MD-300', 'Avaliação de aptidão física e VO2 máximo', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 60),
  ('MD-301', 'Bioimpedância e composição corporal', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 30),
  ('MD-302', 'Prescrição de exercício físico individualizada', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 45),
  ('MD-303', 'Avaliação de lesão esportiva aguda', 'Medicina Esportiva', 'Medicina Esportiva', 'Médico', 45),
  ('MD-304', 'Consulta de acupuntura', 'Medicina Integrativa', 'Acupuntura', 'Médico', 60),
  ('MD-305', 'Sessão de acupuntura – por sessão', 'Medicina Integrativa', 'Acupuntura', 'Médico', 60),
  ('MD-306', 'Auriculoterapia – por sessão', 'Medicina Integrativa', 'Acupuntura', 'Médico', 30),
  ('MD-307', 'Consulta de medicina integrativa / funcional', 'Medicina Integrativa', 'Medicina Funcional', 'Médico', 60),
  ('MD-308', 'Moxabustão – por sessão', 'Medicina Integrativa', 'Acupuntura', 'Médico', 45),
  ('MD-309', 'Consulta de cirurgia plástica', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-310', 'Retorno pós-operatório – cirurgia plástica', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 30),
  ('MD-311', 'Avaliação pré-cirúrgica completa – plástica', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-312', 'Blefaroplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-313', 'Otoplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 45),
  ('MD-314', 'Rinoplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-315', 'Abdominoplastia – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-316', 'Lipoaspiração – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-317', 'Mamoplastia de aumento – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-318', 'Mamoplastia redutora – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-319', 'Lipofilling facial – avaliação e planejamento', 'Cirurgia Plástica', 'Cirurgia Plástica', 'Médico', 60),
  ('MD-320', 'Consulta de fonoaudiologia', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-321', 'Retorno fonoaudiológico', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 30),
  ('MD-322', 'Sessão de fonoaudiologia – voz / disfonia', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-323', 'Sessão de fonoaudiologia – deglutição / disfagia', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-324', 'Sessão de fonoaudiologia – linguagem / gagueira', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-325', 'Terapia miofuncional oral', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 45),
  ('MD-326', 'Avaliação fonoaudiológica completa', 'Fonoaudiologia', 'Fonoaudiologia', 'Médico', 60),
  ('MD-327', 'Consulta de terapia ocupacional', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-328', 'Sessão de terapia ocupacional', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-329', 'Avaliação de independência funcional', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-330', 'Confecção de órtese artesanal', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-331', 'Reabilitação cognitiva – por sessão', 'Terapia Ocupacional', 'Terapia Ocupacional', 'Médico', 60),
  ('MD-332', 'Consulta de genética médica', 'Genética', 'Genética Médica', 'Médico', 60),
  ('MD-333', 'Aconselhamento genético', 'Genética', 'Genética Médica', 'Médico', 90),
  ('MD-334', 'Avaliação de malformação congênita', 'Genética', 'Genética Médica', 'Médico', 60),
  ('MD-335', 'Toxina botulínica – região frontal', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-336', 'Toxina botulínica – glabela – linhas do centro', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-337', 'Toxina botulínica – pés de galinha – por lado', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-338', 'Toxina botulínica – pescoço / platisma – Nefertiti', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-339', 'Toxina botulínica – hiperidrose axilar', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-340', 'Toxina botulínica – hiperidrose palmar', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-341', 'Toxina botulínica – hiperidrose plantar', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-342', 'Toxina botulínica – bruxismo / masseter – ambos', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-343', 'Toxina botulínica – sorriso gengival', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-344', 'Toxina botulínica – mento / queixo', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 20),
  ('MD-345', 'Toxina botulínica – nariz – bunny lines', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 20),
  ('MD-346', 'Toxina botulínica – lábios', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 20),
  ('MD-347', 'Toxina botulínica – pacote testa + glabela + pés de galinha', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-348', 'Preenchimento labial com ácido hialurônico', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-349', 'Preenchimento malar com ácido hialurônico', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-350', 'Preenchimento de olheiras – sulco nasojugal', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-351', 'Preenchimento de bigode chinês – sulco nasolabial', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-352', 'Preenchimento de linha mandibular – jawline', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-353', 'Preenchimento de têmpora – região temporal', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-354', 'Preenchimento de lóbulo auricular', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 30),
  ('MD-355', 'Preenchimento de mãos', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-356', 'Rinomodelação não cirúrgica', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-357', 'Bichectomia', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 90),
  ('MD-358', 'Fio de PDO – por região', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-359', 'Bioestimulador de colágeno – Sculptra / Radiesse', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-360', 'Microagulhamento facial com ativo – por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-361', 'Microagulhamento com PRP – por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 90),
  ('MD-362', 'Luz intensa pulsada IPL – por sessão / área', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-363', 'Laser fracionado – resurfacing por sessão / área', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-364', 'Laser Nd:YAG – vasinhos e melasma por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 45),
  ('MD-365', 'Laser CO2 – cicatrizes / lesões por sessão', 'Estética Médica', 'Dermatologia Estética', 'Médico', 60),
  ('MD-366', 'Criolipólise – por alça / aplicador', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 90),
  ('MD-367', 'Radiofrequência facial – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-368', 'Radiofrequência corporal – por sessão / área', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-369', 'Ultrassom microfocado HIFU – facial', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 90),
  ('MD-370', 'Ultrassom microfocado HIFU – corporal', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 90),
  ('MD-371', 'Eletroestimulação muscular EMsculpt – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 30),
  ('MD-372', 'Mesoterapia capilar – por sessão', 'Estética Médica', 'Tricologia', 'Médico', 60),
  ('MD-373', 'Mesoterapia facial – por sessão', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 45),
  ('MD-374', 'Mesoterapia corporal lipolítica – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-375', 'Carboxiterapia facial – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 45),
  ('MD-376', 'Carboxiterapia corporal – gordura localizada por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-377', 'Ozonioterapia injetável – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 45),
  ('MD-378', 'Drenagem linfática manual – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-379', 'Pressoterapia – por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 45),
  ('MD-380', 'Endermologia – lipomassagem por sessão', 'Estética Médica', 'Medicina Estética Corporal', 'Médico', 60),
  ('MD-381', 'PRP plasma rico em plaquetas – facial', 'Estética Médica', 'Harmonização Orofacial', 'Médico', 60),
  ('MD-382', 'PRP plasma rico em plaquetas – capilar', 'Estética Médica', 'Tricologia', 'Médico', 60),
  ('MD-383', 'Sutura simples – por lesão', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-384', 'Sutura com pontos profundos – por plano', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 45),
  ('MD-385', 'Sutura intradérmica', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 45),
  ('MD-386', 'Retirada de pontos', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 15),
  ('MD-387', 'Drenagem de abscesso cutâneo', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-388', 'Desbridamento de ferida', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-389', 'Infiltração com corticosteroide – por lesão', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 20),
  ('MD-390', 'Retirada de corpo estranho superficial', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 20),
  ('MD-391', 'Exérese de cisto sebáceo / epidermoide', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-392', 'Exérese de lipoma', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 45),
  ('MD-393', 'Exérese de fibroma / molusco contagioso', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 30),
  ('MD-394', 'Cauterização química de lesão', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 15),
  ('MD-395', 'Plástica de cicatriz simples – ambulatorial', 'Pequenas Cirurgias', 'Clínica Geral', 'Médico', 60),
  ('MD-396', 'Curativo simples', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 15),
  ('MD-397', 'Curativo complexo', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 30),
  ('MD-398', 'Flebotomia / coleta de sangue', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-399', 'Aplicação de medicação injetável intramuscular', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-400', 'Aplicação de medicação injetável subcutânea', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-401', 'Aplicação de medicação injetável intravenosa', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-402', 'Infusão venosa – soro ou medicação por hora', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 60),
  ('MD-403', 'Nebulização – por sessão', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-404', 'Aferição de pressão arterial', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 10),
  ('MD-405', 'Oximetria de pulso', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 5),
  ('MD-406', 'Glicemia capilar', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 5),
  ('MD-407', 'ECG técnico de enfermagem', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 15),
  ('MD-408', 'Teste rápido de antígeno covid / gripe / strep', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 15),
  ('MD-409', 'Sondagem nasogástrica', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-410', 'Cateterismo vesical – sondagem vesical', 'Procedimentos Gerais', 'Enfermagem / Clínica', 'Médico', 20),
  ('MD-411', 'Consulta de dor – algologia', 'Algologia', 'Clínica de Dor', 'Médico', 60),
  ('MD-412', 'Retorno algológico', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-413', 'Bloqueio anestésico diagnóstico', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-414', 'Infiltração de ponto gatilho – trigger point', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-415', 'Bloqueio de faceta articular – por nível', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-416', 'Ozônio intraarticular por articulação', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-417', 'Neuroestimulação transcraniana tDCS – por sessão', 'Algologia', 'Clínica de Dor', 'Médico', 30),
  ('MD-418', 'Consulta de medicina física e reabilitação', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 60),
  ('MD-419', 'Retorno reabilitação', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 30),
  ('MD-420', 'Avaliação de incapacidade funcional', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 60),
  ('MD-421', 'Reabilitação cardíaca – consulta e programa', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 45),
  ('MD-422', 'Sessão de reabilitação vestibular', 'Reabilitação', 'Medicina Física e Reabilitação', 'Médico', 45),
  ('MD-423', 'Consulta de sexologia', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-424', 'Retorno sexológico', 'Sexologia', 'Sexologia', 'Médico', 45),
  ('MD-425', 'Avaliação de disfunção sexual masculina', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-426', 'Avaliação de disfunção sexual feminina', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-427', 'Terapia sexual – por sessão', 'Sexologia', 'Sexologia', 'Médico', 60),
  ('MD-428', 'Consulta de cirurgia geral', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 40),
  ('MD-429', 'Retorno cirurgia geral', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 25),
  ('MD-430', 'Avaliação cirúrgica de hérnia', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 40),
  ('MD-431', 'Avaliação de colelitíase – vesícula biliar', 'Cirurgia Geral', 'Cirurgia Geral', 'Médico', 40),
  ('MD-432', 'Consulta de cirurgia bariátrica – avaliação', 'Cirurgia Geral', 'Cirurgia Bariátrica', 'Médico', 60),
  ('MD-433', 'Retorno bariátrico – pós-operatório', 'Cirurgia Geral', 'Cirurgia Bariátrica', 'Médico', 45),
  ('MD-434', 'Check-up executivo – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 120),
  ('MD-435', 'Check-up feminino – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 120),
  ('MD-436', 'Check-up masculino – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 120),
  ('MD-437', 'Check-up pediátrico – avaliação multidisciplinar', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 90),
  ('MD-438', 'Avaliação de risco cardiovascular global', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 45),
  ('MD-439', 'Avaliação de risco oncológico – rastreamento', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 45),
  ('MD-440', 'Programa de cessação do tabagismo – consulta', 'Saúde Preventiva', 'Medicina Preventiva', 'Médico', 45),
  ('MD-441', 'Aplicação de vacina – dose única', 'Saúde Preventiva', 'Imunização', 'Médico', 10),
  ('MD-442', 'Aplicação de vacina – esquema completo três doses', 'Saúde Preventiva', 'Imunização', 'Médico', 30),
  ('MD-443', 'Consulta de neonatologia', 'Neonatologia', 'Neonatologia', 'Médico', 45),
  ('MD-444', 'Avaliação neonatal precoce – 24 a 72 horas', 'Neonatologia', 'Neonatologia', 'Médico', 45),
  ('MD-445', 'Avaliação de icterícia neonatal', 'Neonatologia', 'Neonatologia', 'Médico', 30),
  ('MD-446', 'Consulta de andrologia', 'Andrologia', 'Andrologia', 'Médico', 45),
  ('MD-447', 'Avaliação de infertilidade masculina', 'Andrologia', 'Andrologia', 'Médico', 60),
  ('MD-448', 'Espermograma – avaliação e interpretação', 'Andrologia', 'Andrologia', 'Médico', 30),
  ('MD-449', 'Consulta de tricologia – queda de cabelo', 'Tricologia', 'Tricologia', 'Médico', 45),
  ('MD-450', 'Fototricograma – mapeamento capilar', 'Tricologia', 'Tricologia', 'Médico', 45),
  ('MD-451', 'Ultrassonografia Abdominal Total', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-452', 'Ultrassonografia Pélvica / Transvaginal', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-453', 'Ultrassonografia de Tireoide', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 20),
  ('MD-454', 'Ultrassonografia Mamária', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-455', 'Mamografia Digital', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('MD-456', 'Densitometria Óssea', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 20),
  ('MD-457', 'Raio-X de Tórax', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 15),
  ('MD-458', 'Raio-X de Extremidades', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 15),
  ('MD-459', 'Ressonância Magnética (RM)', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 45),
  ('MD-460', 'Tomografia Computadorizada (TC) Geral', 'Radiologia Médica', 'Radiologia Médica', 'Médico', 30),
  ('OD-131', 'Consulta de Estomatologia', 'Estomatologia', 'Estomatologia', 'Odontológico', 45),
  ('OD-132', 'Aparelho Ortopédico Funcional dos Maxilares', 'Ortopedia Funcional', 'Ortopedia Funcional dos Maxilares', 'Odontológico', 30),
  ('OD-133', 'Terapia Fotodinâmica (PDT) Odontológica', 'Laserterapia', 'Odontologia Geral', 'Odontológico', 20),
  ('OD-134', 'Consulta para Pacientes com Necessidades Especiais', 'Odontologia Especial', 'Pacientes com Necessidades Especiais', 'Odontológico', 60),
  ('OD-135', 'Consulta em Odontogeriatria', 'Odontogeriatria', 'Odontogeriatria', 'Odontológico', 60);

CREATE TABLE IF NOT EXISTS catalog_stock_items (
  id              SERIAL PRIMARY KEY,
  code            TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  category        TEXT,
  clinic_type     TEXT,
  presentation    TEXT,
  frequency_class TEXT
);

ALTER TABLE catalog_stock_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog_stock_read" ON catalog_stock_items
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_catalog_stock_name ON catalog_stock_items USING gin(to_tsvector('portuguese', name));
CREATE INDEX IF NOT EXISTS idx_catalog_stock_cat  ON catalog_stock_items(category);

INSERT INTO catalog_stock_items (code, name, category, clinic_type, presentation, frequency_class) VALUES
  ('ORT-001', 'Braquetes Metálicos (Caso Completo Roth/MBT)', 'Ortodontia', 'Odontologia', 'Kit (20 un)', 'Uso Contínuo'),
  ('ORT-002', 'Braquetes Cerâmicos / Safira', 'Ortodontia', 'Odontologia', 'Kit (20 un)', 'Uso Contínuo'),
  ('ORT-003', 'Fios Ortodônticos NiTi (Níquel-Titânio) - Vários Calibres', 'Ortodontia', 'Odontologia', 'Pacote (10 un)', 'Uso Contínuo'),
  ('ORT-004', 'Fios Ortodônticos Aço Inoxidável', 'Ortodontia', 'Odontologia', 'Pacote (10 un)', 'Uso Contínuo'),
  ('ORT-005', 'Elásticos em Cadeia (Corrente) - Várias Cores', 'Ortodontia', 'Odontologia', 'Rolo', 'Uso Contínuo'),
  ('ORT-006', 'Elásticos Intraorais (Leão, Raposa, etc.)', 'Ortodontia', 'Odontologia', 'Pacote (1000 un)', 'Uso Contínuo'),
  ('ORT-007', 'Alicates Ortodônticos (Corte de Amarrilho, Corte Distal, Weingart)', 'Instrumental Especializado', 'Odontologia', 'Unidade', 'Essencial (Orto)'),
  ('ORT-008', 'Tubos Ortodônticos de Colagem (Simples/Duplos)', 'Ortodontia', 'Odontologia', 'Pacote (10 un)', 'Uso Contínuo'),
  ('IMP-001', 'Implante Cone Morse / Hexágono Externo (Vários Diâmetros)', 'Implantodontia', 'Odontologia', 'Unidade', 'Uso Contínuo'),
  ('IMP-002', 'Kit Cirúrgico de Implantes (Fresas, Chaves, Catraca)', 'Implantodontia', 'Odontologia', 'Kit Completo', 'Essencial (Implante)'),
  ('IMP-003', 'Motor de Implante Odontológico com Bomba Peristáltica', 'Equipamento Cirúrgico', 'Odontologia', 'Unidade', 'Essencial (Implante)'),
  ('IMP-004', 'Enxerto Ósseo Liofilizado (Bovino/Sintético)', 'Cirurgia/Regeneração', 'Odontologia', 'Frasco (0.5g/1g)', 'Procedimento Específico'),
  ('IMP-005', 'Membrana Biológica de Colágeno (Regeneração Óssea Guiada)', 'Cirurgia/Regeneração', 'Odontologia', 'Unidade', 'Procedimento Específico'),
  ('IMP-006', 'Componentes Protéticos (Mini Pilar, Munhão Universal)', 'Implantodontia', 'Odontologia', 'Unidade', 'Reabilitação'),
  ('IMP-007', 'Soro Fisiológico Estéril c/ Equipo (Para Motor de Implante)', 'Cirurgia', 'Odontologia', 'Bolsa', 'Uso Contínuo'),
  ('PER-001', 'Curetas de Gracey (1-2, 5-6, 7-8, 11-12, 13-14)', 'Instrumental Especializado', 'Odontologia', 'Unidade/Kit', 'Essencial (Perio)'),
  ('PER-002', 'Curetas de McCall (13-14, 17-18)', 'Instrumental Especializado', 'Odontologia', 'Unidade/Kit', 'Essencial (Perio)'),
  ('PER-003', 'Sonda Periodontal Milimetrada (Williams/Carolina do Norte)', 'Instrumental de Exame', 'Odontologia', 'Unidade', 'Essencial (Perio)'),
  ('PER-004', 'Sonda de Nabers (Para Furca)', 'Instrumental de Exame', 'Odontologia', 'Unidade', 'Essencial (Perio)'),
  ('PER-005', 'Ponta Ultrassônica Perio (Para Raspador)', 'Acessório Equipamento', 'Odontologia', 'Unidade', 'Uso Contínuo'),
  ('PED-001', 'Coroas de Aço Inoxidável Pré-fabricadas (Infantil)', 'Odontopediatria', 'Odontologia', 'Kit/Unidade', 'Reabilitação Pediátrica'),
  ('PED-002', 'Abridor de Boca Infantil (Bite Block)', 'Acessório', 'Odontologia', 'Unidade', 'Essencial (Odontopediatria)'),
  ('PED-003', 'Fórceps Odontopediátricos (150S, 151S)', 'Instrumental Cirúrgico', 'Odontologia', 'Unidade', 'Essencial (Odontopediatria)'),
  ('PED-004', 'Flúor Diamino de Prata (Cariostático)', 'Odontopediatria', 'Odontologia', 'Frasco', 'Uso Contínuo'),
  ('PED-005', 'Material Restaurador Intermediário (IRM)', 'Restauradora', 'Odontologia', 'Kit', 'Uso Contínuo'),
  ('HOF-001', 'Toxina Botulínica Tipo A (50U, 100U)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Frasco-Ampola', 'Uso Contínuo'),
  ('HOF-002', 'Preenchedor de Ácido Hialurônico (Baixa/Média/Alta Reticulação)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Seringa (1ml)', 'Uso Contínuo'),
  ('HOF-003', 'Fios de Sustentação (PDO - Polidioxanona)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Pacote', 'Uso Contínuo'),
  ('HOF-004', 'Bioestimulador de Colágeno (Ácido Poli-L-Láctico / Hidroxiapatita)', 'Harmonização (HOF)', 'Ambos (HOF/Dermato)', 'Frasco/Seringa', 'Uso Contínuo'),
  ('HOF-005', 'Cânulas para Preenchimento (22G, 25G)', 'Material de Consumo', 'Ambos (HOF/Dermato)', 'Caixa', 'Uso Contínuo'),
  ('GIN-001', 'Espéculo Vaginal Descartável (P, M, G) com parafuso', 'Ginecologia', 'Medicina', 'Caixa (100 un)', 'Uso Contínuo'),
  ('GIN-002', 'Escova Endocervical e Espátula de Ayre (Kit Papanicolau)', 'Ginecologia', 'Medicina', 'Kit', 'Uso Contínuo'),
  ('GIN-003', 'Fixador Citológico Celular (Spray)', 'Ginecologia', 'Medicina', 'Frasco', 'Uso Contínuo'),
  ('GIN-004', 'Lâminas de Vidro com Extremidade Fosca (Citologia)', 'Laboratório', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('GIN-005', 'DIU - Dispositivo Intrauterino (Cobre / Prata / Hormonal)', 'Ginecologia', 'Medicina', 'Unidade', 'Procedimento Específico'),
  ('GIN-006', 'Doppler Fetal Portátil (Sonar)', 'Obstetrícia', 'Medicina', 'Unidade', 'Essencial (Obstetrícia)'),
  ('GIN-007', 'Gel Condutor para Ultrassom/Doppler', 'Ginecologia/Imagem', 'Medicina', 'Galão (5L)', 'Uso Contínuo'),
  ('CAR-001', 'Eletrodos Descartáveis para ECG (Adulto/Infantil)', 'Cardiologia', 'Medicina', 'Pacote (50 un)', 'Uso Contínuo'),
  ('CAR-002', 'Papel Termossensível para Eletrocardiógrafo', 'Cardiologia', 'Medicina', 'Rolo/Bloco', 'Uso Contínuo'),
  ('CAR-003', 'Holter 24h/48h (Aparelho e Gravador)', 'Equipamento Diagnóstico', 'Medicina', 'Unidade', 'Essencial (Cardio)'),
  ('CAR-004', 'M.A.P.A (Monitorização Ambulatorial da Pressão Arterial)', 'Equipamento Diagnóstico', 'Medicina', 'Unidade', 'Essencial (Cardio)'),
  ('CAR-005', 'Braçadeiras Sobressalentes para Esfigmomanômetro (Obeso/Pediátrico)', 'Cardiologia', 'Medicina', 'Unidade', 'Essencial'),
  ('DER-001', 'Dermatoscópio Manual (LED/Polarizado)', 'Dermatologia', 'Medicina', 'Unidade', 'Essencial (Dermato)'),
  ('DER-002', 'Nitrogênio Líquido (Botijão Criogênico e Cautério)', 'Dermatologia', 'Medicina', 'Equipamento/Refil', 'Procedimento Específico'),
  ('DER-003', 'Curetas Dermatológicas Descartáveis (Vários Tamanhos)', 'Dermatologia', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('DER-004', 'Punch para Biópsia de Pele (2mm, 3mm, 4mm, 5mm)', 'Cirurgia Menor', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('DER-005', 'Bisturi Elétrico/Termocautério Portátil', 'Cirurgia Menor', 'Ambos', 'Unidade', 'Essencial'),
  ('ORTP-001', 'Atadura de Gesso (Diversos Tamanhos 10cm, 15cm)', 'Ortopedia', 'Medicina', 'Pacote', 'Uso Contínuo'),
  ('ORTP-002', 'Malha Tubular de Algodão (Diversos Tamanhos)', 'Ortopedia', 'Medicina', 'Rolo', 'Uso Contínuo'),
  ('ORTP-003', 'Algodão Ortopédico (Manta)', 'Ortopedia', 'Medicina', 'Pacote', 'Uso Contínuo'),
  ('ORTP-004', 'Talas Metálicas Forradas com Espuma (Dedo/Punho)', 'Ortopedia', 'Medicina', 'Kit', 'Uso Contínuo'),
  ('ORTP-005', 'Fios de Kirschner (Cirurgia Ortopédica)', 'Cirurgia Maior', 'Medicina', 'Caixa', 'Procedimento Específico'),
  ('ORTP-006', 'Faixa Elástica / Atadura de Crepe', 'Ortopedia/Enfermagem', 'Medicina', 'Pacote', 'Uso Contínuo'),
  ('OFT-001', 'Colírios Diagnósticos (Dilatadores: Tropicamida / Ciclopentolato)', 'Oftalmologia', 'Medicina', 'Frasco', 'Uso Contínuo'),
  ('OFT-002', 'Colírio Anestésico (Proximetacaína)', 'Oftalmologia', 'Medicina', 'Frasco', 'Uso Contínuo'),
  ('OFT-003', 'Tiras de Schirmer (Teste de Secura Ocular)', 'Oftalmologia', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('OFT-004', 'Tiras de Fluoresceína Sódica', 'Oftalmologia', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('OFT-005', 'Caixa de Lentes de Prova e Armação de Teste', 'Equipamento Diagnóstico', 'Medicina', 'Kit Completo', 'Essencial (Oftalmo)'),
  ('OTO-001', 'Espéculos Auriculares (Plástico/Inox - Vários Tamanhos)', 'Otorrino', 'Medicina', 'Kit/Caixa', 'Uso Contínuo'),
  ('OTO-002', 'Espéculo Nasal de Killian', 'Instrumental de Exame', 'Medicina', 'Unidade', 'Essencial (Otorrino)'),
  ('OTO-003', 'Cânulas de Aspiração Auricular (Frazier)', 'Otorrino', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('OTO-004', 'Diapasão Médico (128Hz, 256Hz, 512Hz)', 'Instrumental de Exame', 'Medicina', 'Unidade/Kit', 'Essencial (Neurologia/Otorrino)'),
  ('OTO-005', 'Abaixador de Língua (Palito de Madeira)', 'Exame Físico', 'Ambos', 'Caixa (100 un)', 'Uso Diário'),
  ('URO-001', 'Sonda Vesical de Demora (Foley) - Vários Calibres', 'Urologia/Enfermagem', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('URO-002', 'Sonda de Alívio (Nelaton)', 'Urologia/Enfermagem', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('URO-003', 'Coletor de Urina Sistema Fechado (Bolsa)', 'Urologia/Enfermagem', 'Medicina', 'Unidade', 'Uso Contínuo'),
  ('URO-004', 'Xilocaína Geleia 2% (Lubrificante Uretral)', 'Material de Consumo', 'Medicina', 'Tubo', 'Uso Contínuo'),
  ('EMG-004', 'Cânula de Guedel (Vias Aéreas Orofaringeas - Tamanhos 0 a 5)', 'Emergência', 'Ambos', 'Kit', 'Carrinho de Emergência'),
  ('EMG-005', 'Ressuscitador Manual (Ambu) c/ Máscara Adulto/Pediátrico', 'Emergência', 'Ambos', 'Unidade', 'Carrinho de Emergência'),
  ('EMG-006', 'Tubos Endotraqueais (Com e Sem Balão - Vários Calibres)', 'Emergência/Cirurgia', 'Medicina', 'Caixa', 'Carrinho de Emergência'),
  ('EMG-007', 'Laringoscópio com Lâminas Curvas e Retas (Macintosh/Miller)', 'Emergência', 'Medicina', 'Kit', 'Carrinho de Emergência'),
  ('EMG-008', 'Cateter Venoso Periférico (Jelco / Abocath - 14G a 24G)', 'Enfermagem/Acesso', 'Medicina', 'Caixa', 'Uso Contínuo'),
  ('EMG-009', 'Soro Ringer Lactato / Glicosado 5%', 'Medicação/Fluidos', 'Medicina', 'Bolsa (500ml)', 'Uso Contínuo'),
  ('EMG-010', 'Medicações de Emergência (Adrenalina, Atropina, Amiodarona)', 'Medicação', 'Ambos', 'Ampolas', 'Carrinho de Emergência'),
  ('LAB-001', 'Tubos de Coleta de Sangue (Tampa Roxa - EDTA)', 'Laboratório', 'Medicina', 'Rack (100 un)', 'Exames'),
  ('LAB-002', 'Tubos de Coleta de Sangue (Tampa Amarela/Vermelha - Sorologia)', 'Laboratório', 'Medicina', 'Rack (100 un)', 'Exames'),
  ('LAB-003', 'Tubos de Coleta de Sangue (Tampa Azul - Coagulação)', 'Laboratório', 'Medicina', 'Rack (100 un)', 'Exames'),
  ('LAB-004', 'Agulhas para Coleta Múltipla a Vácuo', 'Laboratório', 'Medicina', 'Caixa', 'Exames'),
  ('LAB-005', 'Adaptador (Canhão) para Coleta a Vácuo', 'Laboratório', 'Medicina', 'Pacote', 'Exames'),
  ('LAB-006', 'Garrote (Torniquete) Elástico', 'Enfermagem/Laboratório', 'Medicina', 'Unidade', 'Uso Contínuo');

CREATE TABLE IF NOT EXISTS catalog_fixed_expenses (
  id              SERIAL PRIMARY KEY,
  code            TEXT NOT NULL UNIQUE,
  category        TEXT,
  description     TEXT NOT NULL,
  type            TEXT,
  periodicity     TEXT,
  estimated_value DECIMAL(10,2),
  recipient       TEXT
);

ALTER TABLE catalog_fixed_expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog_expenses_read" ON catalog_fixed_expenses
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_catalog_exp_name ON catalog_fixed_expenses USING gin(to_tsvector('portuguese', description));
CREATE INDEX IF NOT EXISTS idx_catalog_exp_cat  ON catalog_fixed_expenses(category);

INSERT INTO catalog_fixed_expenses (code, category, description, type, periodicity, estimated_value, recipient) VALUES
  ('INF-001', 'Infraestrutura Clínica', 'Aluguel do Consultório / Clínica', 'Fixo', 'Mensal', 5500, 'Imobiliária'),
  ('INF-002', 'Infraestrutura Clínica', 'Condomínio Comercial', 'Fixo', 'Mensal', 900, 'Administradora'),
  ('INF-003', 'Infraestrutura Clínica', 'IPTU', 'Fixo', 'Mensal', 350, 'Prefeitura'),
  ('INF-004', 'Infraestrutura Clínica', 'Energia Elétrica (Alto consumo por autoclaves/ar condicionado)', 'Híbrido', 'Mensal', 1400, 'Concessionária'),
  ('INF-005', 'Infraestrutura Clínica', 'Água e Esgoto (Taxa comercial)', 'Híbrido', 'Mensal', 300, 'Concessionária'),
  ('INF-006', 'Infraestrutura Clínica', 'Internet Fibra Ótica (Alta estabilidade para Telemedicina)', 'Fixo', 'Mensal', 200, 'Provedor'),
  ('INF-007', 'Infraestrutura Clínica', 'Plano de Celular/WhatsApp Business da Recepção', 'Fixo', 'Mensal', 120, 'Operadora'),
  ('BIO-001', 'Biossegurança e Resíduos', 'PGRSS - Coleta de Lixo Infectante e Perfurocortante', 'Fixo', 'Mensal', 250, 'Empresa de Coleta Especializada'),
  ('BIO-002', 'Biossegurança e Resíduos', 'Dosimetria Pessoal (Monitoramento de Radiação de Raio-X)', 'Fixo', 'Mensal', 150, 'Laboratório de Dosimetria'),
  ('BIO-003', 'Biossegurança e Resíduos', 'Manutenção Preventiva de Equipamentos (Autoclave, Compressor, Cadeira)', 'Fixo', 'Mensal', 400, 'Técnico Especializado'),
  ('BIO-004', 'Biossegurança e Resíduos', 'Controle de Pragas e Dedetização', 'Fixo', 'Trimestral (Rateio Mensal)', 50, 'Dedetizadora'),
  ('TEC-001', 'Tecnologia', 'NaviClin - Plataforma de Gestão e Prontuário Eletrônico', 'Fixo', 'Mensal', 299.9, 'NaviClin'),
  ('TEC-002', 'Tecnologia', 'Sistema PACS/DICOM (Armazenamento de Imagens Radiológicas)', 'Fixo', 'Mensal', 350, 'Provedor Cloud Saúde'),
  ('TEC-003', 'Tecnologia', 'Certificado Digital A1/A3 (Para assinatura de receitas e PEP)', 'Fixo', 'Anual (Rateio Mensal)', 30, 'Certificadora'),
  ('TEC-004', 'Tecnologia', 'Hospedagem de Site e E-mail Corporativo (@naviclin.com)', 'Fixo', 'Mensal', 80, 'Servidor Cloud'),
  ('RH-001', 'Folha de Pagamento', 'Salário: Recepcionista / Secretária Clínica', 'Fixo', 'Mensal', 2200, 'Colaborador'),
  ('RH-002', 'Folha de Pagamento', 'Salário: ASB (Aux. Saúde Bucal) / Técnico de Enfermagem', 'Fixo', 'Mensal', 2500, 'Colaborador'),
  ('RH-003', 'Folha de Pagamento', 'Adicional de Insalubridade (20% sobre Salário Mínimo - ASB/Enfermagem)', 'Fixo', 'Mensal', 282.4, 'Colaborador'),
  ('RH-004', 'Folha de Pagamento', 'Encargos Sociais (INSS, FGTS, etc.)', 'Fixo', 'Mensal', 3200, 'Governo'),
  ('RH-005', 'Folha de Pagamento', 'Provisão de Férias e 13º Salário', 'Fixo', 'Mensal', 700, 'Caixa Clínica'),
  ('RH-006', 'Folha de Pagamento', 'Vale Transporte e Vale Alimentação', 'Fixo', 'Mensal', 1400, 'Operadora de Benefícios'),
  ('RH-007', 'Folha de Pagamento', 'Pró-Labore (Remuneração Fixa dos Sócios/Diretoria)', 'Fixo', 'Mensal', 8000, 'Sócios'),
  ('RH-008', 'Folha de Pagamento', 'Responsabilidade Técnica (RT) - Caso contratado', 'Fixo', 'Mensal', 1500, 'Médico/Dentista RT'),
  ('ADM-001', 'Administrativo e Jurídico', 'Honorários Contábeis (Contabilidade Especializada em Saúde)', 'Fixo', 'Mensal', 1000, 'Escritório de Contabilidade'),
  ('ADM-002', 'Administrativo e Jurídico', 'Seguro de Responsabilidade Civil Profissional (Erro Médico/Odonto)', 'Fixo', 'Mensal', 300, 'Corretora de Seguros'),
  ('ADM-003', 'Administrativo e Jurídico', 'Assessoria de Marketing Médico / Gestão de Tráfego', 'Fixo', 'Mensal', 2000, 'Agência / Freelancer'),
  ('ADM-004', 'Administrativo e Jurídico', 'Faxina / Serviço de Limpeza Hospitalar', 'Fixo', 'Mensal', 1200, 'Terceirizada / Diarista'),
  ('ADM-005', 'Administrativo e Jurídico', 'Segurança Eletrônica (Alarme e Câmeras)', 'Fixo', 'Mensal', 180, 'Empresa de Segurança'),
  ('TAX-001', 'Taxas e Legalização', 'Alvará da Vigilância Sanitária (Provisão Mensal)', 'Fixo', 'Anual (Rateio)', 100, 'Vigilância Sanitária'),
  ('TAX-002', 'Taxas e Legalização', 'Taxa do CNES (Cadastro Nacional de Estabelecimentos de Saúde)', 'Fixo', 'Anual (Rateio)', 50, 'Ministério da Saúde'),
  ('TAX-003', 'Taxas e Legalização', 'Anuidade CRM / CRO da Pessoa Jurídica (Clínica)', 'Fixo', 'Anual (Rateio)', 150, 'Conselho Regional'),
  ('TAX-004', 'Taxas e Legalização', 'Alvará de Funcionamento e Localização da Prefeitura', 'Fixo', 'Anual (Rateio)', 80, 'Prefeitura'),
  ('SUP-001', 'Suprimentos Administrativos', 'Cota - Material de Escritório (Papel A4, Toner para Receitas)', 'Fixo', 'Mensal', 250, 'Papelaria'),
  ('SUP-002', 'Suprimentos Administrativos', 'Cota - Copa e Recepção (Café expresso, água, biscoitos para pacientes)', 'Fixo', 'Mensal', 450, 'Supermercado'),
  ('SUP-003', 'Suprimentos Administrativos', 'Cota - Material de Limpeza Geral', 'Fixo', 'Mensal', 300, 'Distribuidora');
